### ISSUE TITLE
No Apps Display after adding update today

### ISSUE THREAD

**Issue by djughed** [qbcore-framework/qb-phone#101]
![20210913231430_1](https://user-images.githubusercontent.com/22477008/133157300-72098d6b-90c6-4ee6-98ee-cdfff1f1b9b0.jpg)

**Comment by bakerzone** [comment]
I had the exact same, ensure that you update all dependent scripts, all of them, including garage etc

**Comment by djughed** [comment]
thanks will update all and reply once done

**Comment by djughed** [comment]
![image](https://user-images.githubusercontent.com/22477008/133264964-bff15000-c473-41c9-854d-f99d7e13dc31.png)

Modules are updated now. Considering i only started almost a week ago.. I have not gotten this error before. busy looking into it

**Comment by djughed** [comment]
> ![image](https://user-images.githubusercontent.com/22477008/133264964-bff15000-c473-41c9-854d-f99d7e13dc31.png)
> 
> Modules are updated now. Considering i only started almost a week ago.. I have not gotten this error before. busy looking into it

pretty sure im going to have to redeploy with oxymysql as mine is with ghmattimysql

**Comment by bakerzone** [comment]
Afraid so,  I use both for now.

**Comment by djughed** [comment]
ookay.. so redeploy complete and i have updated all the dependancies and imported all sql files but i dont see the new layout.
![20210914171758_1](https://user-images.githubusercontent.com/22477008/133285428-6a7736ff-d863-4fe4-92f6-f0dde0778239.jpg)

**Comment by djughed** [comment]
additional info:
hosted with zap-hosting
deployed with rx-admin recipe https://raw.githubusercontent.com/qbcore-framework/txAdminRecipe/main/qbcore.yaml
updated files manually via ftp

cant seem to see if i did something wrong

**Comment by bakerzone** [comment]
MDT will only be shown if your job is police >>> the other one missing, I've not managed to have that be installed either even if you can see it.
What else do you feel is missing?

**Comment by djughed** [comment]
well im guessing its working. I thought there would be a bit more like photos in twitter.. Think it was more my assumption after that.. closing this out
