### ISSUE TITLE
Change Keybinding

### ISSUE THREAD

**Issue by playamade78** [qbcore-framework/qb-phone#102]
How do you change the keybinding to the phone? It is set to M and I would like to change it to a different key because it conflicts with another program I am using.

**Comment by bakerzone** [comment]
qb-phone > Config > Config.OpenPhone = 244 << change to what you want it to be from here >> https://docs.fivem.net/docs/game-references/controls/

**Comment by playamade78** [comment]
I have tried that and it did not work. I tried using 82 for , and 172 for up arrow and it still was bound to M ingame.

**Comment by ihyajb** [comment]
You can change it in your settings of Gta5. Under the keybind option.

**Comment by P4R4NORM4L** [comment]
It seems like the problem comes from

/resources/[qb]/qb-phone/client/main.lua on line 16 Where it's hard-coded in, whether you change the config or not.. it doesn't matter it will always be M

please fix this

**Comment by P4R4NORM4L** [comment]
I mean to set it default for everyone that joins your server. I'm not talking about personal settings

**Comment by P4R4NORM4L** [comment]
well I must be mistaken then

**Comment by P4R4NORM4L** [comment]
Just tested with a friend and he still has the default M key

**Comment by P4R4NORM4L** [comment]
even after putting 288 as the key

**Comment by jnccloud** [comment]
If someone has previously joined your server then their FiveM is going to remember that keybind. There's a file you can edit to remove it from but I can't recall it. You could create a new profile on your PC and log in from there or reinstall FiveM.

**Comment by jnccloud** [comment]
Not to revive a thread from the dead, but I remembered what that file is called. It stores all of the binds from every server you've joined. Helpful to see what repeats among various servers too if you have issues with people's keybinds not working correctly on your server.

You can open it with sublime or notepad: `%APPDATA%\CitizenFX\fivem.cfg`
