### ISSUE TITLE
why not active InstalledApps

### ISSUE THREAD

**Issue by evanillaa** [qbcore-framework/qb-phone#106]
Hello why not work here download the apps you need
It works on early versions
qb-core line 101
```
	PlayerData.metadata["phonedata"] = PlayerData.metadata["phonedata"] ~= nil and PlayerData.metadata["phonedata"] or {
        SerialNumber = QBCore.Player.CreateSerialNumber(),
        InstalledApps = {},
```

It will be a great feature when it is activated
Before moving to this project, this feature was present in other previous versions

```
["store"] = {
        app = "store",
        color = "#27ae60",
        icon = "fas fa-cart-arrow-down",
        tooltipText = "App Store",
        tooltipPos = "right",
        style = "padding-right: .3vh; font-size: 2.2vh";
        job = false,
        blockedjobs = {},
        slot = 14,
        Alerts = 0,
    },
```

**Comment by darknight2590** [comment]
https://github.com/qbcore-framework/qb-phone/pull/108

**Comment by amgmacht** [comment]
So I did it exactly according to these instructions but it doesn't look nice and after downloading the apps don't end up on the home screen
