### ISSUE TITLE
add qb-notes for qb-phone

### ISSUE THREAD

**Issue by darknight2590** [qbcore-framework/qb-phone#107]
We have in the project a shortage of two scripts and it is very important
The first is his name qb-notes
The second is qb-rental
Regarding the first, the old version of it does not support OneSync
But there is an idea that can be done, which is to integrate it with the phone, and in this way we get rid of the script by integrating it with the phone and supports OneSync.

**Comment by LifeStyleRolePlay** [comment]
This is more so a feature request and not an actual phone issue.
