### ISSUE TITLE
Remove off duty people in apps

### ISSUE THREAD

**Issue by DooubleTap** [qbcore-framework/qb-phone#110]
Would you be able to make sure the mechanics, lawyers and taxi people are not displayed in the call list of said jobs?

**Comment by LifeStyleRolePlay** [comment]
It only shows them on the app when they are on duty, if they go off duty it will not show in the services app

**Comment by DooubleTap** [comment]
yes it does, and they are still paid too. :/

**Comment by Eralpozcan** [comment]
There is nothing wrong. The phone already does this.
