### ISSUE TITLE
New message returning error for the first message to the player

### ISSUE THREAD

**Issue by roobr** [qbcore-framework/qb-phone#112]
local NumberKey = GetKeyByNumber(SenderNumber) returns a nil which is used in a table

        PhoneData.Chats[NumberKey] = {
            name = IsNumberInContacts(SenderNumber),
            number = SenderNumber,
            messages = ChatMessages
        }

SCRIPT ERROR: @qb-phone/client/main.lua:627: table index is nil

**Comment by roobr** [comment]
this is the function that returns nil

function GetKeyByNumber(Number)
    local retval = nil
    if PhoneData.Chats then
        for k, v in pairs(PhoneData.Chats) do
            if v.number == Number then
                retval = k
            end
        end
    end
    return retval
end

**Comment by Bigbearbeasttv** [comment]
Using newest download I was unable to replicate this issue.

**Comment by roobr** [comment]
Thanks, I’ll check it again tonight.. and with update you are referring to the most up to date qb-core
