### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by Mallingdk** [qbcore-framework/qb-phone#121]
Maybe this is a bug.
QB.Phone.Data.PlayerData.money.bank.toFixed is not a function (@qb-phone/html/js/bank.js:50

**Comment by OfficialRDB** [comment]
> 
> 
> Maybe this is a bug. QB.Phone.Data.PlayerData.money.bank.toFixed is not a function (@qb-phone/html/js/bank.js:50
Try this. Go to line 50 in qb-phone/html/js/bank.js

**Replace this:**
`QB.Phone.Data.PlayerData.money.bank = (QB.Phone.Data.PlayerData.money.bank).toFixed();`

**With:**
`var bankAmount = QB.Phone.Data.PlayerData.money.bank;
var amountResult = parseFloat(bankAmount).toFixed();

QB.Phone.Data.PlayerData.money.bank = (amountResult);`
