### ISSUE TITLE
error when try to pay the bill

### ISSUE THREAD

**Issue by Lycanpt** [qbcore-framework/qb-phone#128]
[ERROR] qb-phone was unable to execute a query!
[      script:oxmysql]         Undefined object parameter #2
[      script:oxmysql]         INSERT INTO player_mails (`citizenid`, `sender`, `subject`, `message`, `mailid`, `read`) VALUES (?, ?, ?, ?, ?, ?) {"1":"FMV17452","5":555690,"6":0}

i got this error when someone try to pay a bill.

**Comment by IllInuz** [comment]
@Lycanpt Can you post the codeblock, or give a repro, i was unable to replicate this.
