### ISSUE TITLE
[PHOTO ISSUE] BEWARE BEFORE UPDATING

### ISSUE THREAD

**Issue by GLaZeD-DoHNuTz** [qbcore-framework/qb-phone#148]
Sending photos works perfectly fine, however, you can not delete the photo link in the app!

1) You take a photo and it sends it to Discord and Twitter
2) You try to send another tweet without a photo, and the previous photo is still there!
3) You can not delete that photo link for some reason.

**Comment by V4MPZZ** [comment]
yeah can comfirm this [https://prnt.sc/1z56tnp](url)

**Comment by GhzGarage** [comment]
Should be fixed now
