### ISSUE TITLE
[Feature Suggestion] Custom Photo URL (IMGRR)

### ISSUE THREAD

**Issue by GLaZeD-DoHNuTz** [qbcore-framework/qb-phone#152]
First off, 

Thank you for fixing the Twitter photo issue

As a suggestion, it would be awesome if players can paste a custom URL in the twitter photo link!

Like pasting an imgrr url

**Comment by JericoFX** [comment]
the problem is, you dont have control on what the player can post (imo)

**Comment by GLaZeD-DoHNuTz** [comment]
That's a great point!

**Comment by jnccloud** [comment]
So I was curious about this, I've been using a Discord webhook for over a month now, and every photo is uploaded to a single channel and in the Discord URL, the channel ID is the first number after "attachments" `https://cdn.discordapp.com/attachments/1234567890/XXXXX` - maybe if there was a config option to allow custom URLs when using Discord, but only from channel IDs allowed in the config via an array. Then you could have a channel in your Discord where members can post photos to use in Twitter/Ads and you also sort of get a chance to moderate them. (Deleting a post likely won't delete a photo from Discord's server, but at least you can block the user and restart the phone resource to clear twitter if it was something really bad)

**Comment by GhzGarage** [comment]
Done
