### ISSUE TITLE
[sugestion]

### ISSUE THREAD

**Issue by Branqueador** [qbcore-framework/qb-phone#153]
It would be nice if the tweets would save with and without picture

**Comment by JericoFX** [comment]
https://github.com/qbcore-framework/qb-phone/blob/main/html/js/twitter.js#L117 in this line checks if the tweet has pic or not, what do you mean by "save"?

**Comment by Branqueador** [comment]
> https://github.com/qbcore-framework/qb-phone/blob/main/html/js/twitter.js#L117 in this line checks if the tweet has pic or not, what do you mean by "save"?

so that when you restart the server you still have all the tweets posted

**Comment by JericoFX** [comment]
oohh ok ok, saving the tweets in db

**Comment by Branqueador** [comment]
yes

**Comment by jnccloud** [comment]
I've ran a version of this with and without Twitter being wiped per restart. If Twitter isn't wiped at least daily, all of the photos and text start to slow the phone down quite a bit. At least that was my experience... I guess it could be optimized to load only sections at a time, but I wasn't so sure if the time vs benefit was worth it.

**Comment by Branqueador** [comment]
> I've ran a version of this with and without Twitter being wiped per restart. If Twitter isn't wiped at least daily, all of the photos and text start to slow the phone down quite a bit. At least that was my experience... I guess it could be optimized to load only sections at a time, but I wasn't so sure if the time vs benefit was worth it.

maybe a button ( load more) so that it doesn't get that heavy

**Comment by Gregorsaur** [comment]
Would be great too see this. I'd happily manually purge tweets monthly or sommet if need be
