### ISSUE TITLE
[suggestion] Photo

### ISSUE THREAD

**Issue by OfficialRDB** [qbcore-framework/qb-phone#155]
- Let the player choose if they want to share. So if it gets placed on discord or not.
- Send the player **RP** name with the photo to discord.
- Maybe a watermark on the image bottom right.
- A general photo app, not only a take picture option for twitter, whatsapp ect..

Btw: the border around the photo when you open the photo in-game, doesn't look like it fits.

**Comment by jnccloud** [comment]
For your first point - Discord is only one option... there are plenty of other webhooks to use. Personally, to protect against metagaming, I created a channel reserved for photos that are highly restricted to top-level staff to avoid the entire server seeing all of the photos. The Discord webhook is basically the simplest way to explain it and help someone get started with the photo feature.

**Comment by OfficialRDB** [comment]
> 
> 
> For your first point - Discord is only one option... there are plenty of other webhooks to use. Personally, to protect against metagaming, I created a channel reserved for photos that are highly restricted to top-level staff to avoid the entire server seeing all of the photos. The Discord webhook is basically the simplest way to explain it and help someone get started with the photo feature.

Not sure what your comment is based on.
I only gave a few suggestions.

I never said that discord is the only option, but in general most people will use it with discord.
+ It's a suggestion to give the player the option to share it into the channel or not.

Everybody will use it his own way. I personally will not use a hidden channel for that. I have a channel called city moments.
But that doesn't take away the fact that a suggestion to give players a option to share it or not.

Maybe I weird example, but if your phone provider comes with this new feature that every picture you take gets shared with everybody they want or in 1 place doesn't matter. Without giving you the options if you want that or not, your fine with that ?

**Comment by GhzGarage** [comment]
All that is done through screenshot-basic. Literally nothing to do with the phone
