### ISSUE TITLE
The photo animation is stuck in a loop while taking a twitter pic.

### ISSUE THREAD

**Issue by ShaAlexander** [qbcore-framework/qb-phone#163]
Hi there, 

We found that the twitter, take a pic function makes the character stuck in a loop, maybe there is some if not statement missing?! 

Thanks for considering a fix!

**Comment by DaShizz** [comment]
reproduction: try to take a pic...

**Comment by Eralpozcan** [comment]
Install Screen-shotbasic and your problem will be solved.

**Comment by DaShizz** [comment]
> Install Screen-shotbasic and your problem will be solved.

this is yesterdays build fresh build with the exception of the inventory that i changed cuz im working on it... https://streamable.com/swjs69

**Comment by Eralpozcan** [comment]
I did a new installation yesterday and everything is working in a healthy way. Have you entered your webhook? 
Also, restart your server after screenshot-basic is first installed.

**Comment by DaShizz** [comment]
> I did a new installation yesterday and everything is working in a healthy way. Have you entered your webhook? Also, restart your server after screenshot-basic is first installed.

I was just working on the imgur webhook and just finished it and now it works fine.

It should return an error instead of the animation loop if a hook isnt set up imo..

**Comment by ShaAlexander** [comment]
We already had screenshot-basic installed… but now i have multiple answers from @Eralpozcan and @DaShizz which one, should I pick 👍 ?

**Comment by Eralpozcan** [comment]
Whichever sounds simple to you. The recommended method is to do discord webhook. But you can try other kinds of webhooks. He did it on Imgur.
You can do it with discord webhook first and solve your problem later, if you want, you can use different webhooks as he does.

**Comment by ShaAlexander** [comment]
> Whichever sounds simple to you. The recommended method is to do discord webhook. But you can try other kinds of webhooks. He did it on Imgur.
> You can do it with discord webhook first and solve your problem later, if you want, you can use different webhooks as he does.

Woah fast replay! Many thanks.  

i had copied screenshot-basic from my other server but forgot to remove the Yarn lock file, Yarn.... So did that, let it build restarted and.... nope still stuck in the loop.

**Comment by Eralpozcan** [comment]
Please use the updated version of screenshoot-basic. Don't touch Yarn.

**Comment by Eralpozcan** [comment]
Step by Step
Step 1 : Fresh Start Server. (it's clean, downloaded from the recipe.)
Step 2 : Download ScreentShoot-Basic orjinal repo.
Step 3 : Put Screenshot-basic next to other files.
Step 4:  qb-phone > server.lua > edit webhooks(discord webhooks) and save.
Step 5 : Start your server. 
Step 6 : After all installations and the server are turned on, do not log in, turn off the server, and then turn it back on again.
Step 7 : You can log in after the server is stably turned on. Everything's gonna look normal now.

**Comment by ShaAlexander** [comment]
> **Step by Step** **Step 1 :** Fresh Start Server. (it's clean, downloaded from the recipe.) **Step 2 :** Download ScreentShoot-Basic original repo. **Step 3 :** Put Screenshot-basic next to other files. **Step 4:** qb-phone > server.lua > edit webhooks(discord webhooks) and save. **Step 5 :** Start your server. **Step 6 :** After all installations and the server are turned on, do not log in, turn off the server, and then turn it back on again. **Step 7 :** You can log in after the server is stably turned on. Everything's gonna look normal now.
> 
> _IMPORTANT: Do not use your old resources for this situation. And screenshot-basic needs to be run while the server is starting up._

in step 4, i assume that you mean \qb-phone\server\main.lua?
and then in line 10

`(https://discord.com/api/webhooks/909851513168466002/WOMUm4PVYl6tXjq1sP8zmvXaOrsfTSEeX5v_572-_9N5QGyAMELPryAmT7mae5DFj2_H)' 

and lines 694 to 701 
`QBCore.Functions.CreateCallback("qb-phone:server:GetWebhook",function(source,cb)
	if WebHook ~= "https://discord.com/api/webhooks/909851513168466002/WOMUm4PVYl6tXjq1sP8zmvXaOrsfTSEeX5v_572-_9N5QGyAMELPryAmT7mae5DFj2_H" then
		cb(WebHook)
	else
		cb(nil)
	end

end)`

Or am I completely doing stupid right now? Please feel free to correct me

**Comment by Eralpozcan** [comment]
Dude, all you had to do was enter the local webhooks value above. [Looks](https://prnt.sc/1zowjb0)

**Comment by ShaAlexander** [comment]
> Dude, all you had to do was enter the local webhooks value above. [Looks](https://prnt.sc/1zowjb0)

Oh wait yeah your right hahaha :p

**Comment by DaShizz** [comment]
This need to be modified in a way where if the hook isn't setup, the user would get a notification saying " please reach out to server owner for the setup of this feature" or something to that extent. You're gonna have a lot of nubs not knowing how to setup a webhook or even a simple discord hook

**Comment by Eralpozcan** [comment]
> This need to be modified in a way where if the hook isn't setup, the user would get a notification saying " please reach out to server owner for the setup of this feature" or something to that extent. You're gonna have a lot of nubs not knowing how to setup a webhook or even a simple discord hook

Immediately I'm interested in.
