### ISSUE TITLE
had players moaning

### ISSUE THREAD

**Issue by markbucko12341** [qbcore-framework/qb-phone#179]
people in my server are moaning about  only sending one message  .. they said they have to delete older messages  to be able to send a new message

**Comment by ihyajb** [comment]
sending one message where? Twitter, Ad's? Whatsapp? Need to be a tad more specific. Include any f8 erros (if any)

**Comment by markbucko12341** [comment]
text messages lol .. sorry kinda was in a rush to type it out lol.. but its no big deal to be honest i didnt really check.. i had people say they have to delete pre message  before sending another .. upon inspection  i see what there talking about ... when you type out a message  and send the typed messaged remain in the text box so we have to delete what we had put before.. on the og qb-phone once the message was sent the text box would refresh  so you can type out another message right away lol ... hope this as cleared up the confusion a little more  :)

**Comment by ihyajb** [comment]
Yeah the issue is in the index.html, it's one of the last lines that has to do with emojis, delete that and it should work as normal
