### ISSUE TITLE
Iframe does a bit strange...

### ISSUE THREAD

**Issue by ShaAlexander** [qbcore-framework/qb-phone#183]
Hi there, 

I added the Spotify app, snake and a few others using an Inline frame. Now the fun part. I added the URL https:// not http:// for my own website, and it just won't show up. However! The BBC via blog spot and Spotify via vanity works just fine... 
The F? I'm overloading my brains, on this one, haha! I had this working in the past... but now 😢 

Please any help?!

**Comment by ihyajb** [comment]
Are you using this current qb-phone. The only phone I know that had those apps were from a leak.

**Comment by ShaAlexander** [comment]
Yes it is a vanilla QB phone but, I modified the iPhone (hint) myself, and I bought one, but that was years ago, I just use part of the script the rest is QB original.

**Comment by TexMex100** [comment]
same problem here too
