### ISSUE TITLE
[BUG] Phone not showing

### ISSUE THREAD

**Issue by Tinkiwinky72** [qbcore-framework/qb-phone#189]
All of a sudden i had this major issue with the phone, where it simply would not show up. I havent updated anything. I havent changed anything neither did i add any scripts.
The only way i found to fix this was to delete det player with the issue from the Database. However shortly after it happens again

**Comment by Wisfakim** [comment]
I know this issue with player with low configuration

**Comment by Wisfakim** [comment]
Work with reinstall of all system, for the first connection it's work, after it's broke
