### ISSUE TITLE
Phone pics not working

### ISSUE THREAD

**Issue by ericb160** [qbcore-framework/qb-phone#193]
when i try to take a picture the screen goes in and out and no pic :( fresh install from recipe

**Comment by Vdale73** [comment]
Im having the exact same issue , "no such export requestScreenshotUpload in resource screenshot-basic"

**Comment by JericoFX** [comment]
do you have the screenshot basic resource?

**Comment by Chxttr** [comment]
> do you have the screenshot basic resource?

Yeah I also had the same issue, that's the reason why I reverted to the older phone

Yes, I have and had the sb resource, when upgrading to the new phone I did not update the SB resource, it didn't work, I deleted all server cache, player cache and reinstalled both resources and still did not work, so I went back to the old phone which did work flawleslly

**Comment by ericb160** [comment]
Yea i have screenshot basic :) still doesn't work.

**Comment by ericb160** [comment]
> > do you have the screenshot basic resource?
> 
> Yeah I also had the same issue, that's the reason why I reverted to the older phone
> 
> Yes, I have and had the sb resource, when upgrading to the new phone I did not update the SB resource, it didn't work, I deleted all server cache, player cache and reinstalled both resources and still did not work, so I went back to the old phone which did work flawleslly

Anyway you can send me that phone?

**Comment by Chxttr** [comment]
> > > do you have the screenshot basic resource?
> > 
> > 
> > Yeah I also had the same issue, that's the reason why I reverted to the older phone
> > Yes, I have and had the sb resource, when upgrading to the new phone I did not update the SB resource, it didn't work, I deleted all server cache, player cache and reinstalled both resources and still did not work, so I went back to the old phone which did work flawleslly
> 
> Anyway you can send me that phone?

Message me Chxttr#7137

**Comment by Vdale73** [comment]
i do now , this was my mistake, it works perfectly with ss basic
