### ISSUE TITLE
Phone is not opening on key M

### ISSUE THREAD

**Issue by NL-NoLimit** [qbcore-framework/qb-phone#194]
Some people can open the phone and someone cant open the phone

**Comment by Eralpozcan** [comment]
Is there any error on the console, is Onesyc on?
is qb- core the current version?

**Comment by meistroburger** [comment]
Check the keybinds for FiveM in the settings

**Comment by adhershmnair** [comment]
Same issue for me in latest Linux artifact, In windows local server everything works fine, But Linux artifact failed to load QB Target and QB Phone.

UPDATE: There is no script error or console error.(Literally Zero Error). It is just not working which means not showing the eye icon when we Hold Left Alt. And also QB Phone won’t open. Keybindings are correct, And all the same work with Windows artifact in local.

**Comment by H34R7L3s** [comment]
> Same issue for me in latest Linux artifact, In windows local server everything works fine, But Linux artifact failed to load QB Target and QB Phone.
> 
> UPDATE: There is no script error or console error.(Literally Zero Error). It is just not working which means not showing the eye icon when we Hold Left Alt. And also QB Phone won’t open. Keybindings are correct, And all the same work with Windows artifact in local.

This Issue is still Remaining.
