### ISSUE TITLE
Crypto Abuse Issue

### ISSUE THREAD

**Issue by QuakeAcid** [qbcore-framework/qb-phone#199]
Someone on my server was somehow able to change the amount of crypto he bought using the NUI DevTools and it passed server side

Don't know how to reproduce.

**Comment by Mitroxs** [comment]
> Someone on my server was somehow able to change the amount of crypto he bought using the NUI DevTools and it passed server side
> 
> Don't know how to reproduce.

That was me, but i made a PR to fix it server side which got merged, waiting for my PR on client side of the phone to fix the other part of a similar bug
