### ISSUE TITLE
camera not working properly

### ISSUE THREAD

**Issue by Luceeiy** [qbcore-framework/qb-phone#202]
camera app when you take a picture stays in the open camera and close animation and the phone is in a loop

**Comment by meistroburger** [comment]
I've the same problem, you can't an picture either

**Comment by WEEZOOKARP** [comment]
same issue

**Comment by Chxttr** [comment]
Make sure that you have the Screenshot-basic resource started AND have your webhook added to the server/server.lua @WEEZOOKARP @Luceeiy @meistroburger

**Comment by Chxttr** [comment]
Could you close this issue? @GhzGarage It's fixed since last wave of PRs

**Comment by TinyDerp** [comment]
> Make sure that you have the Screenshot-basic resource started AND have your webhook added to the server/server.lua @WEEZOOKARP @Luceeiy @meistroburger

so... uh... how to add the webhook
my brain no work

**Comment by BlueSky-fur** [comment]
> > Make sure that you have the Screenshot-basic resource started AND have your webhook added to the server/server.lua @WEEZOOKARP @Luceeiy @meistroburger
> 
> so... uh... how to add the webhook my brain no work

Unsure if still relevant, but for anyone wondering 

You can add the webhook under `qb-phone/server/main.lua` in line 9, just add your discord webhook link between the ""
