### ISSUE TITLE
[BUG] tweets not saved into database

### ISSUE THREAD

**Issue by RadhwaneDZ** [qbcore-framework/qb-phone#211]
if you write tweet its not saved to the database after the last PR 
[      script:oxmysql] [ERROR] qb-phone was unable to execute a query!
[      script:oxmysql]         Incorrect datetime value: '2021-12-21T14:26:26.710Z' for column `qbcore`.`phone_tweets`.`date` at row 1
[      script:oxmysql]         INSERT INTO phone_tweets (citizenid, firstName, lastName, message, date, url, picture, tweetid) VALUES ('VQV54992', 'TshoPina', 'Tshopi', 'ned realstate ', '2021-12-21T14:26:26.710Z', '', 'camera-profilepicture', 'TWEET-31058904')

**Comment by Manliketjb** [comment]
Getting the same error

**Comment by Manliketjb** [comment]
Fresh install and still the same problem....

**Comment by RadhwaneDZ** [comment]
are you using linux ?
my main  server installed on linux i have same error 
but in windows no errors tweets inserted to database

**Comment by Manliketjb** [comment]
nope using windows, saving the tweets have never worked for me. Even before they merged the PR, Been nearly 2 weeks and no one has found a fix, then there is the issue if a message has an emoji it doesn't get received or even added to the database.

**Comment by Manliketjb** [comment]
> nope using windows, saving the tweets have never worked for me. Even before they merged the PR, Been nearly 2 weeks and no one has found a fix, then there is the issue if a message has an emoji it doesn't get received or even added to the database.

done some digging and yeah my gameserver is linux

**Comment by tornados1000** [comment]
Head over to qb-phone/server/main.lua on line 955.
Change the line from         TweetData.time,  to         TweetData.date,
This will fix the issue with the incorrect timestamp and SQL update. :)
