### ISSUE TITLE
Vehicles app gives error and don't show any vehicles!

### ISSUE THREAD

**Issue by ShaAlexander** [qbcore-framework/qb-phone#216]
instead of showing vehicles it shows a blank app and in the server log I see this:

![Schermafbeelding 2021-12-28 on 19 06 40](https://user-images.githubusercontent.com/91032578/147594526-d2ce0103-ae1f-46d4-97fc-8a7e0ae53528.png)

**Comment by Branqueador** [comment]
have the same problem

**Comment by Aqade** [comment]
Have same issue - And people are losing their vehicles from the garage somehow. If this is something to do with it.

**Comment by RadhwaneDZ** [comment]
make sure that the car exist  in shared.lua and  player_vehicles

**Comment by Branqueador** [comment]
They are

**Comment by ShaAlexander** [comment]
Yup they are.

**Comment by ShaAlexander** [comment]
some people see them and some don't nowadays...

**Comment by Aqade** [comment]
Yeah, was about to say the same.
- The player buys the vehicle in the shop, which means the car is in the "shared" file. They also get the vehicle in the "player_vehicles" table. But whenever the put it into the garage and try to take it out, its gone. Nowhere to be found, not even impound.

The same guys with the garage script. The error is about the shared vehicle.
But funny thing is, the same car work for some and for some it doesn't.

**Comment by ShaAlexander** [comment]
I don't mind you closing my question but is it fixed yet?

**Comment by 418Gaming** [comment]
Has anyone found a fix for this yet??

**Comment by Prevak** [comment]
why dont we get a answer? this is a big problem, has anyone got it fixed?
