### ISSUE TITLE
Im getting black pictures from the phone when taking a photo

### ISSUE THREAD

**Issue by MaDHouSe79** [qbcore-framework/qb-phone#222]
Hello, i have a question, i have evering installed what is needed for the qb-phone to make puctures, and added the webhook but i get black pictures evertime.

is was working but then suddenly it does not work anymore?

anyone else have the same issue?

**Comment by Klay4** [comment]
@MaDHouSe79 are you using a linux server?

**Comment by whoops1e** [comment]
yes.

**Comment by Klay4** [comment]
@whoops1e please make sure that in your config.lua fiileConfig.Linux is true

**Comment by MaDHouSe79** [comment]
No its a widows for now..

**Comment by F4RRUKO** [comment]
I have the same issue, some fix ?

**Comment by rhapidfyre** [comment]
Also having the same issue. If the player relogs it fixes the issue.. However it's beginning to happen every day. Unable to provide repro steps because it happens to randomly people randomly. Works 4 out of 5 times and then suddenly they're black until they relog.
