### ISSUE TITLE
Races leaderboard

### ISSUE THREAD

**Issue by Sm1l3Punk** [qbcore-framework/qb-phone#231]
Hi,

I would love to know where can i change this so it keeps on the same line and not like this? 
![image](https://user-images.githubusercontent.com/97637722/149226514-c40e36b3-4d48-4d36-ac56-16f24cb8fddb.png)

**Comment by vosscat** [comment]
same to me. waiting for solution.

**Comment by ItsANoBrainer** [comment]
Use the discord for support related questions, Github issues is for issue reports.
