### ISSUE TITLE
when taking photo

### ISSUE THREAD

**Issue by jasini1609** [qbcore-framework/qb-phone#233]
[     script:qb-phone] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:867: No such export fetchSync in resource oxmysql

when i take photo the photo is not shown in gallery. only after relog it shows up.

**Comment by Klay4** [comment]
In server/main.lua edit line 1179 from:
`images = exports.oxmysql:fetchSync('SELECT * FROM phone_gallery WHERE citizenid = ? ORDER BY `date` DESC',{Player.PlayerData.citizenid})`

to:
` local images = MySQL.Sync.fetchAll('SELECT * FROM phone_gallery WHERE citizenid = ? ORDER BY `date` DESC',{Player.PlayerData.citizenid})`

Then open fxmanifest.lua and change server_script to this:
`server_script {
    '@oxmysql/lib/MySQL.lua',
    'server/main.lua'
}`

**Comment by Maureks** [comment]
Hey @Klay4 , I tried your suggestion, and it still does not work.

It gives this error : [     script:qb-phone] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:867: No such export Sync in resource MySQL

**Comment by Klay4** [comment]
@Maureks are you using the last version of oxmysql?

**Comment by Maureks** [comment]
I'm using 1.9.2 version of omxysql , is it because of it ?

**Comment by Klay4** [comment]
@Maureks probably yes, try to download the last version [here](https://github.com/overextended/oxmysql/releases).

**Comment by jasini1609** [comment]
> @Maureks probably yes, try to download the last version [here](https://github.com/overextended/oxmysql/releases).

i have the latest version

now after the changed you suggested 
i get this error 

[      script:oxmysql] SCRIPT ERROR in promise (unhandled): Error: qb-phone was unable to execute a query!
[      script:oxmysql]     You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'BYdate DESC' at line 1
[      script:oxmysql]     SELECT * FROM phone_gallery WHERE citizenid = 'PGQ45038' ORDER BYdate DESC
[      script:oxmysql] > query_default (@oxmysql/dist/server/build.js:16103)
[      script:oxmysql] > processTicksAndRejections (node:internal/process/task_queues:96)
[      script:oxmysql]

**Comment by Maureks** [comment]
I've been searching and the fxmanifest in the oxmysql also says 1.9.2

So now I don't know if mine is up to date , but my guess is, it should be, since i've recreated the server 3/4 days ago , using the latest qb-core framework.

**Comment by Klay4** [comment]
@jasini1609 has the photo been saved in the database?

**Comment by Klay4** [comment]
@Maureks are you sure that you have added 
`server_script {
    '@oxmysql/lib/MySQL.lua',
    'server/main.lua'
}`

in the qb-phone fxmanifest.lua ?

**Comment by Maureks** [comment]
@Klay4 yes , i didn't even had to add it because it already came like that

**Comment by Klay4** [comment]
@Maureks perfect :)

**Comment by jasini1609** [comment]
> @jasini1609 try this one: ` local images = MySQL.Sync.fetchAll('SELECT * FROM phone_gallery WHERE citizenid = ? ORDER BY date DESC',{Player.PlayerData.citizenid})`
> 
> the problem is that github has automatically formatted my text because of the quotes

now i get this error 

[     script:qb-phone] SCRIPT ERROR: @qb-phone/server/main.lua:1178: attempt to index a nil value (global 'MySQL')

**Comment by Klay4** [comment]
@jasini1609 have you edited the fxmanifest?

**Comment by jasini1609** [comment]
> @jasini1609 have you edited the fxmanifest?

now i have.
working perfectly now  

thank you so much!
