### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by CROVVY** [qbcore-framework/qb-phone#236]
Hi, when I take a picture, it doesn't save in phone gallery and this error jump out in console.

Has anyone the solution for this please?

PS: I'm running a Linux server and have in Config.linux = true, webhook is set for discord channel, oxmysql is up-to-date #
![unknown](https://user-images.githubusercontent.com/97665679/149671184-7f708983-42cd-4155-bb87-6219f1158fcb.png)

**Comment by Demo4889** [comment]
what version of oxmysql are you running?

**Comment by CROVVY** [comment]
1.9.3 i guess

**Comment by CROVVY** [comment]
> what version of oxmysql are you running?

1.9.3 i guess

**Comment by Demo4889** [comment]
> > what version of oxmysql are you running?
> 
> 1.9.3 i guess

is that what it says in your fxmanifest for oxmysql?

**Comment by CROVVY** [comment]
> > > what version of oxmysql are you running?
> > 
> > 
> > 1.9.3 i guess
> 
> is that what it says in your fxmanifest for oxmysql?

In fxmanifest is 1.9.2

**Comment by Demo4889** [comment]
in qb-phone server.lua line 1178, change the `fetchSync `to `fetchAll` and see if that fixes your issue.

**Comment by CROVVY** [comment]
> in qb-phone server.lua line 1178, change the `fetchSync `to `fetchAll` and see if that fixes your issue.

Now it says the same but with fetchAll
I'm getting this error about fetch in more scripts like dpemotes or mdt

**Comment by CROVVY** [comment]
I don't know what to do with it

**Comment by Demo4889** [comment]
open your fxmanifest.lua and add `'@oxmysql/lib/MySQL.lua',` to the shared_scripts second. stop your phone, refresh, and then start your phone again. the phone has not been updated to the most recent versions of oxmysql yet.

**Comment by CROVVY** [comment]
> open your fxmanifest.lua and add `'@oxmysql/lib/MySQL.lua',` to the top of the shared_scripts section. stop your phone, refresh, and then start your phone again. the phone has not been updated to the most recent versions of oxmysql yet.

Okey, I'll try. Thank you for the help

**Comment by CROVVY** [comment]
> open your fxmanifest.lua and add `'@oxmysql/lib/MySQL.lua',` to the top of the shared_scripts section. stop your phone, refresh, and then start your phone again. the phone has not been updated to the most recent versions of oxmysql yet.

It didn't help…

**Comment by Jarrad12** [comment]
![image](https://user-images.githubusercontent.com/92127815/152690642-7e31aadc-6dac-4b88-a610-5e73614b0b61.png)

Anyone help me with this? I am using OXMYSQL v1.9.2

**Comment by izMystic** [comment]
why are you asking for help with a core resource in an issue of qb-phone?
Ask in cores discord

**Comment by Jarrad12** [comment]
because ive searched everywhere and i am getting no help from any1 not even the script creator

**Comment by ItsANoBrainer** [comment]
Update your oxmysql, core, and phone.

Use the discord for support related questions, Github issues is for issue reports.
