### ISSUE TITLE
Error in qb-phone.sql

### ISSUE THREAD

**Issue by Galax-One** [qbcore-framework/qb-phone#247]
https://github.com/qbcore-framework/qb-phone/blob/9d8e66f39d3b801fcf82d96b8b4f319b807b57b9/qb-phone.sql#L95
`Invalid default value for 'date'`

**Comment by SmithyPD** [comment]
I have got this error as well for phone_tweets

**Comment by GeekHamza1** [comment]
are you using linux guys ?

**Comment by linzblue1** [comment]
> are you using linux guys ?
![image](https://user-images.githubusercontent.com/5163140/225515801-0bd5eaaf-7ddc-4c23-af37-ecafe4f6d119.png)

Yep getting this error on linux trying to set-up t-admin.
