### ISSUE TITLE
Invoices duplicating

### ISSUE THREAD

**Issue by Texugo97** [qbcore-framework/qb-phone#252]
When i recieve a invoice on qb-phone i have to pay them twice to dissapear from the bank invoices.
Tested with heidisql open, the first time i pay it dissapears from the DB and after that it appears again on phone but nothing is on database.

**Comment by Ziopeppettw** [comment]
Anyone know how to fix?

**Comment by 19adorest** [comment]
still have no idea how to fix this problem, hopefully someone can fix this.

[Duplicating](https://streamable.com/pmpomr)
