### ISSUE TITLE
Error with VehicleData

### ISSUE THREAD

**Issue by ArtysV** [qbcore-framework/qb-phone#255]
G'day everyone! Before 2-3 days I've got this error:
SCRIPT ERROR: @qb-phone/server/main.lua:618: attempt to index a nil value (local 'VehicleData')
[      script:qb-core] > ref (@qb-phone/server/main.lua:618)
[      script:qb-core] > query_default (@oxmysql/dist/server/build.js:16108)
[      script:qb-core] > processTicksAndRejections (node:internal/process/task_queues:96)
I saw in support channels they are asking for fix this error.

**Comment by KriLLTW** [comment]
Did you ever find a fix? Having the same problem

**Comment by JezuzRP** [comment]
any idea on this error???
