### ISSUE TITLE
Vehicle Data Error

### ISSUE THREAD

**Issue by KriLLTW** [qbcore-framework/qb-phone#258]
SCRIPT ERROR: SCRIPT ERROR: @qb-phone/server/main.lua:531: attempt to index a nil value (local 'VehicleData')

This error makes it unable to see the cars people have on their phone. Just happened out of no where.

**Comment by Prevak** [comment]
i have the same problem

**Comment by EXTN-Oxy** [comment]
me too

**Comment by SemperCertusetFidelis** [comment]
Same, I'm suspecting that the car was never stored at a garage after buying it. Not sure if this is the cause yet. Still testing.

**Comment by ScotlandYardRoleplay** [comment]
Did anyone manage to fix this issue?
