### ISSUE TITLE
[Help Wanted] im trying to call using qb-target on phone prop

### ISSUE THREAD

**Issue by zent-M** [qbcore-framework/qb-phone#259]
im trying to make qb-target work on phone prop, the target works i get up the label so the prop set is correct however i cant find what event triggers the call and if what type it is. this is what i have rn but cant make it work.

		options = {
			{
				type = "client",                     <------- this
				event = "qb-phone:server:SetCallState",   <----- and this
				icon = "fas fa-phone",
				label = "call someone in your contacts list",
			}
		},

**Comment by ItsANoBrainer** [comment]
Use the discord for support related questions, Github issues is for issue reports.
