### ISSUE TITLE
Fix tweets saving when you get the sql date error

### ISSUE THREAD

**Issue by SmithyPD** [qbcore-framework/qb-phone#263]
There is an error in the server main.lua line 981.. It says time, and should say date..

	local InsertTweet = MySQL.Async.insert('INSERT INTO phone_tweets (citizenid, firstName, lastName, message, date, url, picture, tweetid) VALUES (?, ?, ?, ?, ?, ?, ?, ?)', {
	TweetData.citizenid,
	TweetData.firstName,
	TweetData.lastName,
	TweetData.message,
	TweetData.time,                         (change this to date to fix the issue)
	TweetData.url,
	TweetData.picture,
	TweetData.tweetId
	})

**Comment by SemperCertusetFidelis** [comment]
Appreciate you sharing this

**Comment by SmithyPD** [comment]
How!? Look at the line Local InsertTweet.. it clearly says date in it and not time.

**Comment by milotiro95** [comment]
I agree with that but after try the tweet not saving. With time it save well so idk.

**Comment by GeekHamza1** [comment]
nice it work

**Comment by Kalizar86** [comment]
I get a query error when trying to save with .time and (NULL) in the date section when saving with .date.  I tried with the config set for linux and the opposite.  Any suggestions?

**Comment by DisguisedOG** [comment]
> TweetData.citizenid,

I did quite the opposite, I changed it back to time and now I can see past tweets.
