### ISSUE TITLE
Moving while Using Phone (Inventory Opens?)

### ISSUE THREAD

**Issue by ch0sguy** [qbcore-framework/qb-phone#265]
I've seen that a similar issue had been closed out due to it being pushed within an update, but I'm still unable to move while the phone is displayed, nor do I see a configuration for this anywhere within the files; I've attempted to add SetNuiFocusKeepInput(true) to the OpenPhone() function, however, this only works until a player attempts to type numbers whilst using, as it prompts the inventory to display/use hotbar items within slots 1-5 (tab also opens the entire inventory).

**Comment by ItsANoBrainer** [comment]
You can not move while the phone is out because there are text fields that require text input which require using your keyboard. If you don't have nui focus input then when you type you hit those keybinds ingame as well. There is no work around.
