### ISSUE TITLE
Broken.

### ISSUE THREAD

**Issue by 0x43b** [qbcore-framework/qb-phone#266]
Qb-phone is discontinued and no longer works across all servers. Must pay for ESX phones now for them to work in GTAV rp. Just a heads up to not waste your time with this. The uploader couldnt even be bothered to finish the install guide. Trash.

**Comment by SmithyPD** [comment]
This isnt ESX...

**Comment by YeahItsHayden** [comment]
If you're having issues with the phone, use the TXAdmin install recipe, the phone isn't discontinued and plenty of people use it without issues 👍

**Comment by ItsANoBrainer** [comment]
Closed for brigading and spreading false information.
