### ISSUE TITLE
Attempt to concatenate a nil value (field 'sender')

### ISSUE THREAD

**Issue by divide29** [qbcore-framework/qb-phone#268]
When accepting a bill the bill sender get the following error:
Attempt to concatenate a nil value (field 'sender')
client/main.lua:1525

**Comment by erikmeyer08** [comment]
I'm also having this issue.

![image](https://user-images.githubusercontent.com/43043270/159141050-3f64254f-2c74-4c5b-8fb7-3a3a59372f19.png)

**Comment by L4wlz** [comment]
I also get this error. Are your guys also getting the bland undefined email ?

**Comment by L4wlz** [comment]
Found out you need to add the job you are at in the commision part in the config file.. i dont get the error anymore..
