### ISSUE TITLE
Cannot take photos and save to gallery OR post to twitter.

### ISSUE THREAD

**Issue by novasobored** [qbcore-framework/qb-phone#269]
Hi! I'm currently having an issue where phone pictures will not load. It comes up as this small icon, and no photo actually shows up on twitter or in the photo gallery. I have [screenshot-basic] in my resources folder, I also added a Discord webhook in the config. Is there something I am missing? Thanks![][(url)] (https://imgur.com/a/GfgqTaH)

**Comment by Zack41199** [comment]
Same here but my phones keep spamming open and closed as soon as i take a picture. Anyone know how to fix

**Comment by GhzGarage** [comment]
You didn’t add the webhook

**Comment by novasobored** [comment]
> 

I did actually! And it still isnt working. I also ensured basic-screenshot in the server config and the photos still will not work.

**Comment by novasobored** [comment]
> You didn’t add the webhook

I did actually! And it still isnt working. I also ensured basic-screenshot in the server config and the photos still will not work.

**Comment by Zack41199** [comment]
Also when i add cars to the vehicles.lua it deletes all of the cars in the shop. if i replace the cars in the vehicles.lua it works but i want to add, not replace

**Comment by anonymonstr** [comment]
has anyone resolved the issue with camera issue please?

**Comment by Shotgunner187** [comment]
any fix yet? Still happening for me,
