### ISSUE TITLE
problems to add job to mdt acces 

### ISSUE THREAD

**Issue by bimbolaki** [qbcore-framework/qb-phone#276]
I don't know if it's me who isn't the correct syntax but I don't think so.
1) impossible to declare several jobs in access to mdt/meos.
-- job = {"police", "sheriff", "marshal"}, --
= no ok, no more jobs have access

2) I also tested with blocked job by declaring all the other jobs there,
-- blockedjobs = {"mechanic", "unemployed", "ambulance", "realestate", "taxi", "bus", "cardealer", "judge", "lawyer", "reporter"}, --
=no ok all job have access

do you have a suggestion?

**Comment by cqmpact** [comment]
Just add a new entry to config and change the name of the table entry.

```
  ["meos"] = {
        app = "meos",
        color = "#004682",
        icon = "fas fa-ad",
        tooltipText = "MDT",
        job = "police",
        blockedjobs = {},
        slot = 13,
        Alerts = 0,
    },
      ["meostwo"] = {
        app = "meos",
        color = "#004682",
        icon = "fas fa-ad",
        tooltipText = "MDT",
        job = "anotherpolicejob",
        blockedjobs = {},
        slot = 13,
        Alerts = 0,
    },
```

**Comment by bimbolaki** [comment]
you're great thanks , i love you :)
