### ISSUE TITLE
past tweets not showing?

### ISSUE THREAD

**Issue by twigmasters** [qbcore-framework/qb-phone#280]
I saw the bug post about the error causing tweets not to save in the database and fixed that but I noticed If I post a tweet, log out then back in, the tweet is gone? 

I know there is a setting for time tweets will show but logging out and back is just minutes apart. Is this normal or should past tweets stay a while even if you log out?

**Comment by DisguisedOG** [comment]
Having the same issue.

**Comment by TakeFiveGames** [comment]
Remove the '?' parameter for date around line 826 and the one below that, and replace it with `NOW()`

The insertion for some reason uses the date from the script and MySQL does not like that.

**Comment by Brotatochips11** [comment]
> Remove the '?' parameter for date around line 826 and the one below that, and replace it with `NOW()`. The insertion for some reason uses the date from the script and MySQL does not like that.
> 
> Change:
> 
> ```
> 'INSERT INTO phone_tweets (citizenid, firstName, lastName, message, date, url, picture, tweetid) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'
> ...
> 'INSERT INTO phone_tweets (citizenid, firstName, lastName, message, date, url, picture, tweetid) VALUES (?, ?, ?, ?, ?, ?, ?, ?)',
> ```
> 
> to
> 
> ```
> 'INSERT INTO phone_tweets (citizenid, firstName, lastName, message, date, url, picture, tweetid) VALUES (?, ?, ?, ?, NOW(), ?, ?, ?)
> ...
> 'INSERT INTO phone_tweets (citizenid, firstName, lastName, message, date, url, picture, tweetid) VALUES (?, ?, ?, ?, NOW(), ?, ?, ?)'
> ```
> 
> and then remove "TweetData.date" and "TweetData.time" from the parameters

This worked for me

**Comment by markkhoo** [comment]
was there a PR for this?
