### ISSUE TITLE
[HELP] Making this script work with SaltyChat

### ISSUE THREAD

**Issue by W0lv3sxD** [qbcore-framework/qb-phone#286]
Hey,

I need help changing this script to work with SaltyChat.

What I tried before was changing this

exports['pma-voice']:removePlayerFromCall(PhoneData.CallData.CallId)
exports['pma-voice']:addPlayerToCall(PhoneData.CallData.CallId)

to this

exports['saltychat']:EndCall(PhoneData.CallData.CallId)
exports['saltychat']:EstablishCall(PhoneData.CallData.CallId)

but I'm getting the errors "no such export EndCall in saltychat" "no such export EstablishCall in saltychat" even though they exist in saltychat. I was told that should ask you how to change it... I dont think that it's on you but maybe you can help me out.

Thanks in advance.

**Comment by WilliamFalci** [comment]
#359 This pull request have it :D
