### ISSUE TITLE
Screenshot Black photo

### ISSUE THREAD

**Issue by milotiro95** [qbcore-framework/qb-phone#287]
Hey everyone.

For several days I have had a problem with qb-phone when I take a photo 1 / 2 photo or more is sent to my discord bot with a black image instead of the photo. Does anyone encounter the problem? My discord bot is correctly set since it sends one out of two photos and the problem only appeared a few days ago. I use the official version of qb-phone and screenshot-basic

When i got the black pictures I try a screenshot with ZDiscord bot and also got a black screen and it works normally again for no reason so I think the problem come from Screenshot-basic

**Comment by milotiro95** [comment]
Which merge is fixing this problem @GhzGarage ?

**Comment by peppinoita** [comment]
Have you tried to update the screenshots-basic resource?

**Comment by milotiro95** [comment]
Of course as I said it's totally random sometimes it's work and another it will just stop work and send black pictures (save also in the gallery).
