### ISSUE TITLE
App no show

### ISSUE THREAD

**Issue by Christina1734** [qbcore-framework/qb-phone#291]
![image](https://user-images.githubusercontent.com/61150247/167232177-9a3b5990-aa27-451e-aae2-d730ca5a8fe7.png)
I suddenly into this mess, still not fixed even update to latest ver of qb-phone.
no error code shows up no mater restart the script or simply use the key to open phone.

**Comment by bertux30** [comment]
Same problem, did you fix it?

**Comment by Christina1734** [comment]
> Same problem, did you fix it?
Got this fixed, simply change the 'Config' words of the entire script to another one will fix this issue.
Guess that the reason of this malfunction is because the config.lua is include the other script, that cause the Config table is too large? I'm not sure of it, anyway I got this done LOL

**Comment by DuckyOnThatQuack** [comment]
I had the same problem, turns out, it's from you and not the server. Try getting a friend to join and test the phone, it will work. Simply clear you FiveM cache and remake your character and you're golden :)

**Comment by Ryguystreams** [comment]
would anyone know why my apps wasnt poppin up i put the original .lua file an switched charaters, but now i cant put it away? like it tries but pulls it out and wont move at all at that point!

**Comment by MazeRPserver** [comment]
i fixed it !! delete garages from ur fxmanifest.lua

**Comment by Rtextbook** [comment]
> i fixed it !! delete garages from ur fxmanifest.lua

same problem and the second i hashed that out and restarted the resource its working again. how can we let them know whats up with that. for some repair or support
