### ISSUE TITLE
[BUG] Add job on Service in qb-phone

### ISSUE THREAD

**Issue by Arpanbarai21** [qbcore-framework/qb-phone#294]
I want to add a job status like cardealer on services in qb-phone. Please help me

**Comment by slideyboii33** [comment]
id also really like to know how to do this

**Comment by klose2410** [comment]
I like to know that to

**Comment by F4ngb0n3** [comment]
Nothing on this yet? I have a taxi service I want to add to the phone, but the comments are unclear as to steps needed to take.

**Comment by Brotatochips11** [comment]
Its kind of a lengthy process, but I can possibly make a youtube tutorial for all of you here in a day or two.
@slideyboii33 @klose2410 @F4ngb0n3 @Arpanbarai21

**Comment by F4ngb0n3** [comment]
> Its kind of a lengthy process, but I can possibly make a youtube tutorial for all of you here in a day or two. @slideyboii33 @klose2410 @F4ngb0n3 @Arpanbarai21

No worries! As I was looking through the code, I realized just how lengthy of a process it can really be -- no skin off my shoulders if I need to wait, but tbh I found a work around and it works fluidly (well, more like a sludgey kinda fluid) with your resource lol either way though, I appreciate the reachout!

**Comment by klose2410** [comment]
Yeees pleas make a YouTube


fre. 24. jun. 2022 00.49 skrev Brotatochips11 ***@***.***>:
