### ISSUE TITLE
[BUG] calls does not start error "the person is not available"

### ISSUE THREAD

**Issue by peppinoita** [qbcore-framework/qb-phone#306]
**Describe the bug**
Sorry for opening an issue, but I can't find any info related to this issue. If i call a contact or directly type the number the call fails immediately with message "the person is not available". If I call using the job feature it works. Can this be related to the new phone number change?

**To Reproduce**
1. Open contact
2. Click on call a contact
3. you get the message "the person is unavailable"

**Expected behavior**
The call should go to the called person.

**Screenshots**
No screenshot

**Questions (please complete the following information):**
 - When you last updated: as soos as a new update is released
 - Are you using custom resource? which ones? no
 - Have you renamed `qb-` to something custom? no

**Comment by peppinoita** [comment]
Just found this post on discord that seems related to my issue:

_after updating qb-core and qb-phone
When a new citizen is created - you can not call them.
the old citizen before the change can be called.
anyone have an idea for this?

but if i change the line 
`PlayerData.charinfo.phone = PlayerData.charinfo.phone or QBCore.Functions.CreatePhoneNumber()
`
to

`PlayerData.charinfo.phone = PlayerData.charinfo.phone ~= nil and PlayerData.charinfo.phone or '' .. math.random(11111111, 99999999)`

And remove 

```
function QBCore.Functions.CreatePhoneNumber()
    local UniqueFound = false
    local PhoneNumber = nil
    while not UniqueFound do
        PhoneNumber = math.random(11111111,99999999)
        local query = '%' .. PhoneNumber .. '%'
        local result = MySQL.prepare.await('SELECT COUNT(*) as count FROM players WHERE charinfo LIKE ?', { query })
        if result == 0 then
            UniqueFound = true
        end
    end
    return PhoneNumber
end
```

then it works._

**Comment by peppinoita** [comment]
Just for additionale info I'm on Ubuntu 20.04 with 5632 artifacts and of course i set true on lunux option in the phone

**Comment by LateNightRP** [comment]
I am having this same issue now. It just started today when I updated the core and a few other scripts. Phone contacts says everyone is offline. Just the job center contacts work just fine. Attached is a photo of the error codes we are getting.

https://cdn.discordapp.com/attachments/956649776487751680/987889616252174406/error_phone_1.png

**Comment by Deadgaminglive** [comment]
same, i jusr update my core last night and today all contacts offline but can call thru services

**Comment by Howsn** [comment]
Same problem after updating core. Tried rollbacking the update but still dosent work 😩

**Comment by LateNightRP** [comment]
We added the old core back and we get the same results as well

**Comment by peppinoita** [comment]
Since some last pr whene the phone number generation was converted to a number instean a text string, we forget to convert the 'number' field to number instead of string in the function GetPlayerByPhone(number) so to fix you have to:

on qb-core/server/functions.lua

find

```
function QBCore.Functions.GetPlayerByPhone(number)
    for src, _ in pairs(QBCore.Players) do
        if QBCore.Players[src].PlayerData.charinfo.phone == number then
            return QBCore.Players[src]
        end
    end
    return nil
end
```

and replace with:

```
function QBCore.Functions.GetPlayerByPhone(number)
    for src, _ in pairs(QBCore.Players) do
        if QBCore.Players[src].PlayerData.charinfo.phone == tonumber(number) then
            return QBCore.Players[src]
        end
    end
    return nil
end
```

in other word replace `number` with `tonumber(number)`

I need to thank BruinStar (on guilded, yes guilded rocks, few people but really effective) that helped me reach to this fix. I hope this will help you.

**Comment by Howsn** [comment]
> I am having this same issue now. It just started today when I updated the core and a few other scripts. Phone contacts says everyone is offline. But the job center contacts work just fine. Attached is a photo of the error codes we are getting.
> 
> https://cdn.discordapp.com/attachments/956649776487751680/987889616252174406/error_phone_1.png

I have the same error as you. Also after I did the last fix.

**Comment by peppinoita** [comment]
Yes this is a new issue. It is related to contact picture. This can also be related to number format.

**Comment by Howsn** [comment]
> 

You wanna team up and try to find a fix?

**Comment by mhnl3** [comment]
> That fixed the issue of being able to call people. But now it seems like its not pulling the name when people call you instead. Looked at the functions but couldn't really figure out where to make a change for that.

**Comment by mhnl3** [comment]
> Yes this is a new issue. It is related to contact picture. This can also be related to number format.



> Since some last pr where the phone number generation was converted to a number instead of a text string, we forget to convert the 'number' field to number instead of string in the function GetPlayerByPhone(number) so to fix you have to:
> 
> on qb-core/server/functions.lua
> 
> find
> 
> ```
> function QBCore.Functions.GetPlayerByPhone(number)
>     for src, _ in pairs(QBCore.Players) do
>         if QBCore.Players[src].PlayerData.charinfo.phone == number then
>             return QBCore.Players[src]
>         end
>     end
>     return nil
> end
> ```
> 
> and replace with:
> 
> ```
> function QBCore.Functions.GetPlayerByPhone(number)
>     for src, _ in pairs(QBCore.Players) do
>         if QBCore.Players[src].PlayerData.charinfo.phone == tonumber(number) then
>             return QBCore.Players[src]
>         end
>     end
>     return nil
> end
> ```
> 
> in other word replace `number` with `tonumber(number)`
> 
> I need to thank BruinStar (on guilded, yes guilded rocks, few people but really effective) that helped me reach to this fix. I hope this will help you.



That fixed the issue of being able to call people. But now it seems like its not pulling the name when people call you instead. Looked at the functions but couldn't really figure out where to make a change for that.

**Comment by LateNightRP** [comment]
That fixed the online player issue. I am still getting some of these error codes tho?

https://cdn.discordapp.com/attachments/956649776487751680/987889616252174406/error_phone_1.png

**Comment by peppinoita** [comment]
A PR has been made and accepted for the original issue.

There are additional issues opened for the others questions, so I close this as complete.
