### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Kuwuz** [qbcore-framework/qb-phone#307]
I've added this to my server and everything works except for contacts, I can't actually click the confirm button when entering a contact, there isn't any errors with this, it just doesn't give Me an option to click confirm

**Comment by midz8** [comment]
Have you inserted the sql? Also it should look like this once you have finished making your contact. It should say save not confirm.
![Desktop Screenshot 2022 06 19 - 13 55 31 81 (2)](https://user-images.githubusercontent.com/73448760/174462726-32d49fdc-2f81-4bef-81ce-94e48e74f6c9.png)
