### ISSUE TITLE
[BUG] im getting a error each time i restart my server

### ISSUE THREAD

**Issue by xReaperModzz** [qbcore-framework/qb-phone#309]
(nil stack trace)SCRIPT ERROR: SCRIPT ERROR: @qb-phone/server/main.lua:199: attempt to index a nil value (field 'Vehicles')
[      script:qb-core] > ref (@qb-phone/server/main.lua:199)
[      script:qb-core] > Query.onResult (@oxmysql/dist/build.js:21740)
[      script:qb-core] > <unknown> (@oxmysql/dist/build.js:11918)
[      script:qb-core] > processTicksAndRejections (node:internal/process/task_queues:78)

^^^^it gives me that error in the live consol ^^^^
also when i try to go in the dealership neither one allows me to view the categories

**Comment by finneusfk124** [comment]
did you find fix i have exact same problem
