### ISSUE TITLE
[BUG] Cant send messages

### ISSUE THREAD

**Issue by Zael98** [qbcore-framework/qb-phone#310]
When i send a message i have this error, but when i send THE FIRST message all work fine, when in the phone_messages are 1 row, the phone stop to work fine. Anyone know why? happen with all the phones and in a fresh install with txadmin
![Sin título](https://user-images.githubusercontent.com/28166060/174658895-36d24c04-3e76-4e92-b3b5-d623353e18ba.png)

**Comment by Howsn** [comment]
> When i send a message i have this error, but when i send THE FIRST message all work fine, when in the phone_messages are 1 row, the phone stop to work fine. Anyone know why? happen with all the phones and in a fresh install with txadmin ![Sin título](https://user-images.githubusercontent.com/28166060/174658895-36d24c04-3e76-4e92-b3b5-d623353e18ba.png)

I have the same problem, happend after the last core udpate. Let me know if you find a fix.

**Comment by peppinoita** [comment]
Same on my side

**Comment by Howsn** [comment]
> Same on my side

I see, I dont get whye a rollback dosent work for me. I tried putting back my old core but then I cant call anyone again.
It looks like when I run the new core it messed something up.

**Comment by Zael98** [comment]
i tried a lot of cores, artifacts, phones and no one work, idk what happen  :/

**Comment by Zael98** [comment]
@Deadgaminglive No, i dont have any fix to the bug for the moment :(

**Comment by peppinoita** [comment]
Can you try to replace this?
Sorry for the screenshot but guilder does not allow me to copy text from mobile
![Screenshot_20220621-232813_Guilded](https://user-images.githubusercontent.com/12203647/174900751-99f67ffa-5873-4344-a4b1-0d9913557790.png)

**Comment by peppinoita** [comment]
We shoult start testing to add tonumber( ... ) in any value that require a phone number and find which is the one not rec as number

**Comment by Howsn** [comment]
> We shoult start testing to add tonumber( ... ) in any value that require a phone number and find which is the one not rec as number

I can help you if you need a person to test with.
