### ISSUE TITLE
[BUG] Nil value (local 'vehicledata')

### ISSUE THREAD

**Issue by jokernights** [qbcore-framework/qb-phone#312]
**Describe the bug**
A clear and concise description of what the bug is. A stranger to qbcore should be able to read your bug report and understand how to reproduce it themselves and understand how the feature should work normally.

**To Reproduce**
1. Go to 'phone '
2. Click on 'ping or other areas'
3. Use this item 
4. See error SCRIPT ERROR: SCRIPT ERROR: @qb-phone/server/main.lua:630: attempt to index a nil value (local 'VehicleData')

**Expected behavior**

I updated everything and it fixed the calling issue of saying not available but now Ping doesn't work and other things. i also now get a black screen when taking pictures, may be unrelated but the original issue now works but get a ton of errors when using other apps on the phone

**Screenshots**

![image](https://user-images.githubusercontent.com/77025615/174926538-0096af0a-6a6e-4142-8cf6-a85a99bacb0a.png)

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week]
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target]
 - Have you renamed `qb-` to something custom? [e.g. yes/no]

**Additional context**

**Comment by jokernights** [comment]
Any updates on this?

**Comment by finneusfk124** [comment]
any news to fix it

**Comment by Getpwnedbydolbajoba** [comment]
Hi! Have u tried to install new version of qb-phone?

**Comment by davoucci** [comment]
i got the same problem and i tried to install the new version, same thing. I got this bug when i'm trying to see my vehicle in the phone app.

**Comment by whoru33** [comment]
any update on this fix? I have a fully functional phone outside of this issue.
