### ISSUE TITLE
[BUG] After "tonumber(number)" issue i got new with whatsapp and save contacts

### ISSUE THREAD

**Issue by killarabg** [qbcore-framework/qb-phone#313]
after adding the fix for the phone call the following happened 
now they can't write messages and do not see them 
also when you call a reserved number, its telephony number appears, not the name of the saved contact
![image](https://user-images.githubusercontent.com/46526996/175161916-23235f24-c408-42ba-a423-3b0c5ad9e326.png)
![image](https://user-images.githubusercontent.com/46526996/175162262-1e014e20-8892-4113-941d-bcd55c9689c0.png)

please help if you can :(

**Comment by Howsn** [comment]
We are manny people who have this problem. Hoping for a fix soon, because removing the tonumber dident work for some reason..

**Comment by killarabg** [comment]
> We are manny people who have this problem. Hoping for a fix soon, because removing the tonumber dident work for some reason..

I hope to find a solution soon as you know I guess people are very pretentious and now constantly complain that the phone does not work well i have server with 500ppl and i got many hating :(

**Comment by nzkfc** [comment]
Tell me about it haha

**Comment by peppinoita** [comment]
https://github.com/qbcore-framework/qb-core/issues/736#issuecomment-1169945411
