### ISSUE TITLE
[BUG] This person is not available! after qb-core update

### ISSUE THREAD

**Issue by Howsn** [qbcore-framework/qb-phone#315]
**Describe the bug**
After the redo on the tonumber for the phone we still have the same problem.
This person is not available, and you cant send whatsapp messages.
The player that is online is also red on the contact list and you get error in the phone client.lua line 1862.

**To Reproduce**
1. Go to 'Go to contactlist and try to call someone that is online on the  server'
3. Use this item '....' (item's name from shared.lua if applicable)

**Expected behavior**

**Screenshots**
https://gyazo.com/c7008ce843ba046c82663d6a06fcee28

**Questions (please complete the following information):**
 - When you last updated: [latest qb-core update]
 - Are you using custom resource? which ones? [no]
 - Have you renamed `qb-` to something custom? [no]

**Additional context**

**Comment by Howsn** [comment]
Was anyone able to fix this problem?

**Comment by MaDHouSe79** [comment]
well this `local Target = QBCore.Functions.GetPlayerByPhone(number)` always returns nil, even if the player is online and stand next to me,, but when i reverse engineering, it, to find the issue..

i found out that the `CallData = {},` is always `false false` or `false false false`

and cause the Target = nil the CallData will return false at anytime, cause there is no target that is return from the `QBCore.Functions.GetPlayerByPhone(number)` function, and i tond know if the new Offline stuff in player.lua has something to do with it, cause the player is alwayes offline.

**Comment by Howsn** [comment]
> well this `local Target = QBCore.Functions.GetPlayerByPhone(number)` always returns nil, even if the player is online and stand next to me,, but when i reverse engineering, it, to find the issue..
> 
> i found out that the `CallData = {},` is always `false false` or `false false false`
> 
> and cause the Target = nil, so the CallData will return false at anytime, cause there is no target that is return from the `QBCore.Functions.GetPlayerByPhone(number)` function, and i dont know if the new Offline stuff in player.lua has something to do with it, cause the player is alwayes offline.

I see, I'm not sure the new offline stuff have something to do with it 🤔 I tried reverting back to my old core without the offline stuff and had the same ressult. But good work finding this, will try and look more into it.

**Comment by MaDHouSe79** [comment]
> > well this `local Target = QBCore.Functions.GetPlayerByPhone(number)` always returns nil, even if the player is online and stand next to me,, but when i reverse engineering, it, to find the issue..
> > i found out that the `CallData = {},` is always `false false` or `false false false`
> > and cause the Target = nil, so the CallData will return false at anytime, cause there is no target that is return from the `QBCore.Functions.GetPlayerByPhone(number)` function, and i dont know if the new Offline stuff in player.lua has something to do with it, cause the player is alwayes offline.
> 
> I see, I'm not sure the new offline stuff have something to do with it 🤔 I tried reverting back to my old core without the offline stuff and had the same ressult. But good work finding this, will try and look more into it.

I found out if you change this

```lua
PlayerData.charinfo.phone = tonumber(PlayerData.charinfo.phone) or QBCore.Functions.CreatePhoneNumber()
````
TO
```lua
PlayerData.charinfo.phone = PlayerData.charinfo.phone or QBCore.Functions.CreatePhoneNumber()
```

in player.lua you can calll again, on my server everting is working again ;)

**Comment by Howsn** [comment]
I think i found the problem.
In the database all the number for player that have been online when the tonumber fix was in have change to
"phone\":123456789.

And this is how it was befor the tonumber fix:
"phone\":\"123456789

So the fix is to export the player tabs and change ( "phone\": ) to ( "phone\":\" ) and import it again.
I hope :D

Let me know what you think.

**Comment by TankinTom** [comment]
How did you remove the phone data and not have it completely fuck up the DB?
