### ISSUE TITLE
[BUG] Phone ringing as number instead of saved contact name

### ISSUE THREAD

**Issue by nzkfc** [qbcore-framework/qb-phone#316]
**Describe the bug**
When someone in your contacts calls, it shows number not name

**To Reproduce**
1. Add contact
2. Get them to call you
3. Shows number instead of name

**Expected behavior**
Name appears if contact saved

**Questions (please complete the following information):**
 - When you last updated: 22nd June
 - Are you using custom resource? which ones? N/A
 - Have you renamed `qb-` to something custom? No

**Additional context**
We noticed an update for some number code, merged that in from latest and the issue is the same.

**Comment by Deadgaminglive** [comment]
same
