### ISSUE TITLE
[BUG] Phone invoices re-appearing after paying / declining

### ISSUE THREAD

**Issue by Diversey** [qbcore-framework/qb-phone#317]
**Describe the bug**
The phone invoices are re-appearing after you pay / decline them

**To Reproduce**
1. Open the banking app > invoices after getting an invoice from a player
2. Pay the invoice which successfully gets rid of the invoice
3. Re-open the app or the phone
4. The invoice is back in your invoices and you can choose to pay it again
5. The invoice is finally gone after having to pay, or decline it twice

**Expected behavior**
The invoice should clear as soon as it's paid / declined

**Questions (please complete the following information):**
 - When you last updated: April, updated the whole server to newest QB core
 - Are you using custom resource? which ones? qb-phone-np-edit however the functionality of the phone is almost the same.
 - Have you renamed `qb-` to something custom? no

**Comment by Diversey** [comment]
anyone? Still struggling to fix this.

**Comment by xchopin** [comment]
I have the same issue I will make my own fix at this point

**Comment by Zilockegaming** [comment]
ihave the same issue also i tried to let my taxi`s give bills to the customers

**Comment by 19adorest** [comment]
this problem has been around for too long and there is still no solution
