### ISSUE TITLE
Phone invoices not appearing

### ISSUE THREAD

**Issue by LifeStyleRolePlay** [qbcore-framework/qb-phone#32]
When you do /bill and send an invoice to them it will let you but the other person will not be able to see that invoice unless qb-phone is restarted

**Comment by tsegkos** [comment]
Yes, it doesn't work for me either. I have the same issue.

**Comment by nylanpro** [comment]
me too

**Comment by GhzGarage** [comment]
Update your phone and sql for phone_invoices and let me know if the problem is still there

**Comment by LifeStyleRolePlay** [comment]
I have the newest phone, along with the most recent SQL uploaded and invoices still don't show unless the phone is restarted

**Comment by nylanpro** [comment]
the error is still there, has not been improved, used the latest version and full sql - > https://streamable.com/3ncx33

**Comment by SW1FT** [comment]
Works for me.
