### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by finneusfk124** [qbcore-framework/qb-phone#324]
[      script:qb-core] (nil stack trace)SCRIPT ERROR: SCRIPT ERROR: @qb-phone/server/main.lua:199: attempt to index a nil value (field 'Vehicles')
[      script:qb-core] > ref (@qb-phone/server/main.lua:199)
[      script:qb-core] > <unknown> (@oxmysql/dist/build.js:21729)
[      script:qb-core] > processTicksAndRejections (node:internal/process/task_queues:96)
[      script:qb-core] > async rawQuery (@oxmysql/dist/build.js:21719)

i got this error after adding a add on car to the share/vehicle.lua and when ever i go to the dealer ship it wont let me browse any of the cars and sorta breaks qbcore and it happens on any add on car when i add one

**Comment by Deadgaminglive** [comment]
> [ script:qb-core] (nil stack trace)SCRIPT ERROR: SCRIPT ERROR: @qb-phone/server/main.lua:199: attempt to index a nil value (field 'Vehicles') [ script:qb-core] > ref (@qb-phone/server/main.lua:199) [ script:qb-core] > (@oxmysql/dist/build.js:21729) [ script:qb-core] > processTicksAndRejections (node:internal/process/task_queues:96) [ script:qb-core] > async rawQuery (@oxmysql/dist/build.js:21719)
> 
> i got this error after adding a add on car to the share/vehicle.lua and when ever i go to the dealer ship it wont let me browse any of the cars and sorta breaks qbcore and it happens on any add on car when i add one

your doing something wrong when adding them, make sure everything is correct, car name, spawn name in every location in vehicle lua and name of dealership, doing this wrong or forgetting a comma or some other mark will cause this too
