### ISSUE TITLE
QB-Phone Camera

### ISSUE THREAD

**Issue by Pintta** [qbcore-framework/qb-phone#326]
Qb-Phone Camera is not working, this going move loop and crash a game for player.

**Comment by JericoFX** [comment]
Did you add the webhook?

**Comment by theCowBoiCoder** [comment]
I also have had the issue with the phone camera looping and it only goes away if you re log

**Comment by Pintta** [comment]
I've added the webhook links, but the camera still goes into an even worse loop, that this qb-phone is a bad thing for the camera.

**Comment by Pintta** [comment]
> I also have had the issue with the phone camera looping and it only goes away if you re log

But it has not been fixed, already there the camera is completely messed up. I have taken this latest Update, still the camera pulls a loop, also tested with 40 different other players, same thing.

**Comment by MirageRP** [comment]
was this resolved? as having the same issue and unsure how to fix? cheers

**Comment by Pintta** [comment]
> was this resolved? as having the same issue and unsure how to fix? cheers

I fixed that long ago for better and add more things what helping for players.
https://github.com/Pintta/qb-phone
