### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Svenhr** [qbcore-framework/qb-phone#327]
**Describe the bug**
Go in twitter and post something you post will be on twitter but you have error in console.

**To Reproduce**
1. Go to 'Go in twitter and post something '
3. Use this item '....' (item's name from shared.lua if applicable)

**Expected behavior**

**Screenshots**
https://i.imgur.com/IufXgTx.png

**Questions (please complete the following information):**
 - When you last updated: [laterst version via txadmin]
 - Are you using custom resource? which ones? [im using all default script donwloaded via txadmin]
 - Have you renamed `qb-` to something custom? [no]

**Additional context**

**Comment by JericoFX** [comment]
Try to import the sql again

**Comment by Svenhr** [comment]
Hi i deleted all my server files and database and install again via txadmin and nothing is changed same error

**Comment by cory1768** [comment]
I think this is related to an old issue that was resolved. Check out this one:
"
Head over to qb-phone/server/main.lua on line 955.
Change the line from TweetData.time, to TweetData.date,
"
https://github.com/qbcore-framework/qb-phone/issues/211

I had the same issue and it corrected it for me.

**Comment by Svenhr** [comment]
Fixed it by upgrade the mysql version server to 8.0.30

**Comment by maej20** [comment]
My fix for this was to change ```./qb-phone/html/js/twitter.js:217``` from
```javascript
var CurrentDate = new Date();
```

to 

```javascript
var date = new Date();
var CurrentDate = date.toISOString().slice(0, 19).replace('T', ' ');
```
