### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by 0411447** [qbcore-framework/qb-phone#328]
Seem to be having issues with the APP store. I can't seem to see it on the phone however I see coding in the config that would suggest it might to talk to QB-Territories. Any suggestions

**Comment by sinphoenix** [comment]
Have you tried to replace the script itself?

**Comment by 0411447** [comment]
> Have you tried to replace the script itself? 

Yep, updated with the most recent version

**Comment by maej20** [comment]
app store is not yet implemented
