### ISSUE TITLE
why delete this ?

### ISSUE THREAD

**Issue by darknight2590** [qbcore-framework/qb-phone#33]
RegisterServerEvent('police:server:CheckBills')
AddEventHandler('police:server:CheckBills', function()
    local src = source
    local Player = QBCore.Functions.GetPlayer(src)
    exports.ghmattimysql:execute('SELECT * FROM bills WHERE citizenid=@citizenid AND type=@type', {['@citizenid'] = Player.PlayerData.citizenid, ['@type'] = 'police'}, function(result)
        if result[1] ~= nil then
            local totalAmount = 0
			for k, v in pairs(result) do
				totalAmount = totalAmount + tonumber(v.amount)
            end
            Player.Functions.RemoveMoney("bank", totalAmount, "paid-all-bills")
            exports.ghmattimysql:execute('DELETE FROM bills WHERE citizenid=@citizenid AND type=@type', {['@citizenid'] = Player.PlayerData.citizenid, ['@type'] = 'police'})
            TriggerClientEvent('police:client:sendBillingMail', src, totalAmount)
            TriggerEvent('qb-moneysafe:server:DepositMoney', "police", totalAmount, "bills")
		end
	end)
end)

**Comment by GhzGarage** [comment]
Billing system is now in the phone
