### ISSUE TITLE
[BUG] Taking a picture with the phone camera

### ISSUE THREAD

**Issue by cory1768** [qbcore-framework/qb-phone#332]
**Describe the bug**
I have configured local WebHook ="" in the config with my webhook inside of the quotes. I then restarted the server to make the configuration change live. When any user goes to take a camera picture the phone will simply sit and spin. I am able to exit this by pressing esc and the phone returns to normal operation. But the images are never captured or saved.

A clear and concise description of what the bug is. A stranger to qbcore should be able to read your bug report and understand how to reproduce it themselves and understand how the feature should work normally.

In an attempt to understand what is going on I went to [qb]\qb-phone\client\main.lua > then on line 1403 I added "print(data) -- Debug Code" (Without quotes.) This printed the following response: (Also see error02.png as well)

MainThrd/ {"code":"BadRequestError","message":"must provide either content or embeds to create webhook message"}
MainThrd/ ^1SCRIPT ERROR: @qb-phone/client/main.lua:1406: attempt to index a nil value (field 'attachments')^7
MainThrd/ ^3> ref^7 (^5@qb-phone/client/main.lua^7:1406)
MainThrd/ ^3> <unknown>^7 (^5@screenshot-basic/dist/client.js^7:1)

**To Reproduce**
1. Go to '[qb]\qb-phone\server\main.lua'
2. Edit line 9 where it says local WebHook = ""
3. Add in your webhook inside of the quotes
4. Save the file
5. Restart the server
6. Log into the server, open the phone, and attempt to take a picture with your phone. (See error01.png)

**Expected behavior**
I would expect the image to get loaded with the webhook and for the photo to successfully save in the database.

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week] 
 - 8/16/2022
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] 
 - No
 - Have you renamed `qb-` to something custom? [e.g. yes/no] 
 - No

**Additional context**

![error01](https://user-images.githubusercontent.com/29211582/186271105-0f8985e6-248e-4899-99e1-f0c48152eb73.png)
![error02](https://user-images.githubusercontent.com/29211582/186271107-865f8365-3eaa-4622-8de7-70d8bea94b5f.png)

**Comment by singh-manavv** [comment]
maybe you entered the webhook wrong , because this only happens if the webhook isn't added
