### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ckaysone380** [qbcore-framework/qb-phone#334]
**Describe the bug**
Some characters that are created are not getting phone numbers assigned to them

**To Reproduce**
1. Go to 'Character creation'
2. Click on 'Create or save'
3. Use this item 'hit m for phone'
4. See error or no error and phone number shows up as NIL

**Comment by singh-manavv** [comment]
Can't reproduce the issue , it works fine in my server , make sure everything is latest
