### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Zilockegaming** [qbcore-framework/qb-phone#336]
doen not know where to send money after giving a player the bill
![unknown](https://user-images.githubusercontent.com/98334361/188319450-ea1f1ad9-df85-462f-98b6-0a2ec0deafba.png)

Describe the bug
The phone invoices are given to a player but when that player trys to pay

To Reproduce

Open the banking app > invoices after getting an invoice from a player
Pay the invoice and open F8 commandprompt to see the error
Re-open the app or the phone
The invoice is still in your invoices and you can choose to pay it again
The invoice is gone after decline
Expected behavior
The invoice should clear as soon as it's paid

Questions (please complete the following information):

When you last updated: November , updated the whole server to newest QB core
Are you using custom resource? which ones? qb-royalpolicejob i made my self however the functionality of the phone is almost the same. the MDT on the phone is not workinf for this job but that is not nessesary
Have you renamed qb- to something custom? no

**Comment by tom-osborne** [comment]
Please specify the steps taken to create this error. We cannot help without extra information.

**Comment by Zilockegaming** [comment]
Describe the bug
The phone invoices are given to a player but when that player trys to pay

To Reproduce
Steps to reproduce the behavior:

Open the banking app > invoices after getting an invoice from a player
Pay the invoice and open F8 commandprompt to see the error
Re-open the app or the phone
The invoice is still in your invoices and you can choose to pay it again
The invoice is  gone after  decline
Expected behavior
The invoice should clear as soon as it's paid

Questions (please complete the following information):

When you last updated: November , updated the whole server to newest QB core
Are you using custom resource? which ones? qb-royalpolicejob i made my self however the functionality of the phone is almost the same. the MDT on the phone is not workinf for this job but that is not nessesary
Have you renamed qb- to something custom? no
