### ISSUE TITLE
adding job in qb-phone

### ISSUE THREAD

**Issue by hybridgamer** [qbcore-framework/qb-phone#337]
### The problem

I don't know if anyone here can help me I've been having a problem for hours I'm trying to add a job in the qb-phone lawyers.js but I keep crashing on the same problem the number won't come in the list the job itself is in the list but the phone number of the job is not showing

### Ideal solution

that the job i have add workt and i can se in my server the phone numbers of the job

**Comment by hydrorp** [comment]
how would i go about doing this?
