### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by TankinTom** [qbcore-framework/qb-phone#345]
### Summary

Services

### Reproduction

Open the phone, click services

### Expected behavior

You can see the people logged in with those positions

### Actual behavior

it works

### Additional context

Is there a way to edits the services and add custom jobs? Our server has 3 different mech shops, and they're all labeled differently, and have different "jobs". When all the jobs are set to mechanic, they all appear. I was in the main.lua, and tried this, to no avail:
QBCore.Functions.CreateCallback('qb-phone:server:GetCurrentLawyers', function(_, cb)
    local Lawyers = {}
    for _, v in pairs(QBCore.Functions.GetPlayers()) do
        local Player = QBCore.Functions.GetPlayer(v)
        if Player ~= nil then
            if (Player.PlayerData.job.name == "lawyer" or Player.PlayerData.job.name == "realestate" or
                Player.PlayerData.job.name == "tappin" or Player.PlayerData.job.name == "taxi" or
                Player.PlayerData.job.name == "dillinger" or Player.PlayerData.job.name == "ezauto" or
                Player.PlayerData.job.name == "police" or Player.PlayerData.job.name == "ambulance") and
                Player.PlayerData.job.onduty then
                Lawyers[#Lawyers+1] = {
                    name = Player.PlayerData.charinfo.firstname .. " " .. Player.PlayerData.charinfo.lastname,
                    phone = Player.PlayerData.charinfo.phone,
                    typejob = Player.PlayerData.job.name

### Last Updated

week ago

### Custom Resources

N/A

### Resource Rename

No

**Comment by Pompier48495052** [comment]
hello for its not only necessary to add it it is also necessary to add it in your html file js lawyers.js

**Comment by Pompier48495052** [comment]
and if you want to add it you have to go to the lua in the server and then you go to the js you add it to the lawyers-list you add it to the data function after you take the example line of code

$(".lawyers-list").append('<h1 style="font-size:1.641025641025641vh; padding:1.0256410256410255vh; color:#fff; margin-top:0; border-top-left-radius: . 5vh; border-top-right-radius: .5vh; width:100%; display:block; background-color: rgb(42, 137, 214);">Lawyers (' + lawyers.length + ')</h1 >');

         if (lawyers. length > 0) {
             $.each(lawyers, function(i, lawyer) {
                 var element = '<div class="lawyer-list" id="lawyerid-' + i + '"> <div class="lawyer-list-firstletter" style="background-color: rgb(42, 137, 214 );">' + (lawyer.name).charAt(0).toUpperCase() + '</div> <div class="lawyer-list-fullname">' + lawyer.name + '</div> < div class="lawyer-list-call"><i class="fas fa-phone"></i></div> </div>'
                 $(".lawyers-list").append(element);
                 $("#lawyerid-" + i).data('LawyerData', lawyer);
             });
         } else {
             var element = '<div class="lawyer-list"><div class="no-lawyers">There are no lawyers available.</div></div>'
             $(".lawyers-list").append(element);
         }

and you change what you need but place it before the else which is at the bottom otherwise it will make you an error and you will not have any service

**Comment by Pompier48495052** [comment]
# @TankinTom

**Comment by TankinTom** [comment]
Closing this as we ended up changing phones, so now it doesn't matter.
