### ISSUE TITLE
this phone_tweets in database not using

### ISSUE THREAD

**Issue by darknight2590** [qbcore-framework/qb-phone#35]
this phone_tweets in database not using

**Comment by cienar** [comment]
qb-phone is not saving tweets and adverts

**Comment by darknight2590** [comment]
We hope that the data will be stored in the database
or through json

**Comment by JericoFX** [comment]
im working on a sistem to save twitter to json and do a picture stuff

**Comment by darknight2590** [comment]
Please take into consideration
This topic can also be used with the application of ads and whatsapp
I wish you success and thank you to all the volunteers for this beautiful project
