### ISSUE TITLE
[BUG] Qb phone camera not saving images

### ISSUE THREAD

**Issue by RKDimitrov** [qbcore-framework/qb-phone#363]
### Summary

When I take a photo in twitter a small icon of image comes up and i cant open it. Same happens when i take a regular photo in the camera app. The webhook is working because it sends the image in a discord channel

### Reproduction

1. I was using qb-phone

2. Just setup the webhook

3. The phone does not show the actual images in twitter nor camera app
![image](https://user-images.githubusercontent.com/99919461/218876197-bc581c0e-b6ac-4e6c-95f3-6b95764f5335.png)
![image](https://user-images.githubusercontent.com/99919461/218876237-d6e983aa-73d1-4f80-8e12-8597611b697c.png)

4. The webhook shows the images in discord
![image](https://user-images.githubusercontent.com/99919461/218875915-27e3b0da-f79a-407d-be58-b06009c9435a.png)

### Expected behavior

It should have shown me the images in the phone

### Actual behavior

It doesn't show any images in the phone, only in the webhook discord channel

### Last Updated

Today

### Custom Resources

qb-phone, screenshot-basic

### Resource Rename

No, i have not it is qb-phone

**Comment by Eviltjuuh** [comment]
FIX
• go to qb-phone
• open fxmanifest.lua
• find fx_version 'cerulean'
• change that into fx_version 'bodacious'

**Comment by Binho92** [comment]
eviltjuuh bro thank u for this !!!!! im opening my server and this phone was broken. many thanks is not enough!!! <3

**Comment by zwkf** [comment]
Fixed
https://github.com/qbcore-framework/qb-phone/pull/362
