### ISSUE TITLE
[BUG] SCRIPT ERROR: @qb-phone/client/main.lua:1058: attempt to index a nil valua (field 'RaceData)

### ISSUE THREAD

**Issue by Jacky3316** [qbcore-framework/qb-phone#367]
### Summary

 I use create track but get this error

### Reproduction

Help me!

### Expected behavior

![image](https://user-images.githubusercontent.com/101520909/223999050-36a737bb-97fd-4dc7-bcb5-cf996a93ff6c.png)

### Actual behavior

Help me

### Last Updated

Today

### Custom Resources

qb-lapraces

### Resource Rename

no

**Comment by gnika** [comment]
https://github.com/qbcore-framework/qb-lapraces/issues/39 et ca marche :)
