### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by CengizKocer** [qbcore-framework/qb-phone#371]
### The problem

why does this not work? am i doing it wrong?

  ["crewmenu"] = {
        app = "crewmenu",
        color = "#CF007D",
        icon = "fas fa-crown",
        tooltipText = "crew yonetim",
        job = false,
        blockedjobs = {},
        slot = 8,
        Alerts = 0,
        data = {
            action = "crewmenu",
        },

### Ideal solution

can you help me out ?

### Additional context

please help me

**Comment by ChristianBDev** [comment]
You forgot a } at the end, you closed out action but not the whole crew menu.

**Comment by ChristianBDev** [comment]
If you use visual studio code, there’s an extension called error lens that will help you as well! @CengizKocer

**Comment by CengizKocer** [comment]
> 

Nope i already had it like that 

{
        app = "crewMenu",
        color = "#CF007D",
        icon = "fas fa-crown",
        tooltipText = "crew menu",
        job = false,
        blockedjobs = {},
        slot = 8,
        Alerts = 0,
        data = {
            action = "/crewMenu"
        }
    },

**Comment by CengizKocer** [comment]
nah i cant get it to work....

**Comment by CengizKocer** [comment]
> If you use visual studio code, there’s an extension called error lens that will help you as well! @CengizKocer

i like blackbox and genie :D

**Comment by ChristianBDev** [comment]
So you have it in this format?

`["crewmenu"] = {
    app = "crewmenu",
    color = "#CF007D",
    icon = "fas fa-crown",
    tooltipText = "crew yonetim",
    job = false,
    blockedjobs = {},
    slot = 8,
    Alerts = 0,
    data = {
        action = "crewmenu",
    },
}`

**Comment by ChristianBDev** [comment]
Cause apparently its wrong, if you think my example of the fix is not right

**Comment by CengizKocer** [comment]
This is what i got also the licensemenu not working too can someone please show me what is wrong?

Config.PhoneApplications = {
    ["phone"] = {
        app = "phone",
        color = "#04b543",
        icon = "fa fa-phone-alt",
        tooltipText = "Phone",
        tooltipPos = "top",
        job = false,
        blockedjobs = {},
        slot = 1,
        Alerts = 0,
    },
    ["whatsapp"] = {
        app = "whatsapp",
        color = "#25d366",
        icon = "fas fa-comment",
        tooltipText = "Whatsapp",
        tooltipPos = "top",
        style = "font-size: 2.8vh";
        job = false,
        blockedjobs = {},
        slot = 2,
        Alerts = 0,
    },
    ["settings"] = {
        app = "settings",
        color = "#636e72",
        icon = "fa fa-cogs",
        tooltipText = "Settings",
        tooltipPos = "top",
        style = "padding-right: .08vh; font-size: 2.3vh";
        job = false,
        blockedjobs = {},
        slot = 3,
        Alerts = 0,
    },
    ["twitter"] = {
        app = "twitter",
        color = "#1da1f2",
        icon = "fab fa-twitter",
        tooltipText = "Twitter",
        tooltipPos = "top",
        job = false,
        blockedjobs = {},
        slot = 4,
        Alerts = 0,
    },
    ["garage"] = {
        app = "garage",
        color = "#575fcf",
        icon = "fas fa-car",
        tooltipText = "Vehicles",
        job = false,
        blockedjobs = {},
        slot = 5,
        Alerts = 0,
    },
    ["mail"] = {
        app = "mail",
        color = "#ff002f",
        icon = "fas fa-envelope-open-text",
        tooltipText = "Mail",
        job = false,
        blockedjobs = {},
        slot = 6,
        Alerts = 0,
    },
    ["advert"] = {
        app = "advert",
        color = "#ff8f1a",
        icon = "fas fa-bullhorn",
        tooltipText = "Advertisements",
        job = false,
        blockedjobs = {},
        slot = 7,
        Alerts = 0,
    },
    ["crewmenu"] = {
        app = "crewmenu",
        color = "#CF007D",
        icon = "fas fa-crown",
        tooltipText = "crew yonetim",
        job = false,
        blockedjobs = {},
        slot = 8,
        Alerts = 0,
        data = {
            action = "crewMenu",
        },
    },
    ["bank"] = {
        app = "bank",
        color = "#9c88ff",
        icon = "fas fa-money-check-alt",
        tooltipText = "Bank",
        job = false,
        blockedjobs = {},
        slot = 9,
        Alerts = 0,
    },
    ["crypto"] = {
        app = "crypto",
        color = "#004682",
        icon = "fas fa-coins",
        tooltipText = "Crypto",
        job = false,
        blockedjobs = {},
        slot = 10,
        Alerts = 0,
    },
    ["racing"] = {
        app = "racing",
        color = "#353b48",
        icon = "fas fa-flag-checkered",
        tooltipText = "Racing",
        job = false,
        blockedjobs = {},
        slot = 11,
        Alerts = 0,
    },
    ["houses"] = {
        app = "houses",
        color = "#27ae60",
        icon = "fas fa-home",
        tooltipText = "Houses",
        job = false,
        blockedjobs = {},
        slot = 12,
        Alerts = 0,
    },
    ["meos"] = {
        app = "meos",
        color = "#004682",
        icon = "fas fa-ad",
        tooltipText = "MDT",
        job = "police",
        blockedjobs = {},
        slot = 13,
        Alerts = 0,
    },
    ["lawyers"] = {
        app = "lawyers",
        color = "#26d4ce",
        icon = "fas fa-briefcase",
        tooltipText = "Services",
        tooltipPos = "bottom",
        job = false,
        blockedjobs = {},
        slot = 14,
        Alerts = 0,
    },
    ["gallery"] = {
        app = "gallery",
        color = "#AC1D2C",
        icon = "fas fa-images",
        tooltipText = "Gallery",
        tooltipPos = "bottom",
        job = false,
        blockedjobs = {},
        slot = 15,
        Alerts = 0,
    },
    ["camera"] = {
        app = "camera",
        color = "#AC1D2C",
        icon = "fas fa-camera",
        tooltipText = "Camera",
        tooltipPos = "bottom",
        job = false,
        blockedjobs = {},
        slot = 16,
        Alerts = 0,
    },
    ["licensemenu"] = {
        app = "Lisans TC",
        color = "#FF0000",
        icon = "fas fa-certificate",
        tooltipText = "licensemenu",
        tooltipPos = "bottom",
        job = "police",
        blockedjobs = {},
        slot = 17,
        Alerts = 0,
        data = {
            action = "/licensemenu",
        },
    },
}
Config.MaxSlots = 20
