### ISSUE TITLE
 Warning: could not find file html/fonts/*.ttf  ,  html/fonts/*.otf ,  html/fonts/*.woff (defined in fxmanifest.lua:25)

### ISSUE THREAD

**Issue by Rtextbook** [qbcore-framework/qb-phone#372]
### Summary

[  resources:qb-phone] Warning: could not find file `html/fonts/*.ttf` (defined in fxmanifest.lua:25) [  resources:qb-phone] Warning: could not find file `html/fonts/*.otf` (defined in fxmanifest.lua:25) [  resources:qb-phone] Warning: could not find file `html/fonts/*.woff` (defined in fxmanifest.lua:25) [           resources] Started resource qb-phone (3 warnings)

### Reproduction

nothing complete new txadmin recipe load of qbcore

[  resources:qb-phone] Warning: could not find file `html/fonts/*.ttf` (defined in fxmanifest.lua:25)
[  resources:qb-phone] Warning: could not find file `html/fonts/*.otf` (defined in fxmanifest.lua:25)
[  resources:qb-phone] Warning: could not find file `html/fonts/*.woff` (defined in fxmanifest.lua:25)
[           resources] Started resource qb-phone (3 warnings)

### Expected behavior

going to -- out the files in manifest for now. 

### Actual behavior

going to -- out the files in manifest for now. 

### Last Updated

today

### Custom Resources

qbcore 

### Resource Rename

qb-phone

**Comment by MuskyTV** [comment]
Same issue here

**Comment by JawshuaW** [comment]
same issue.
