### ISSUE TITLE
qb phone not working nor is hud 

### ISSUE THREAD

**Issue by madmechanic187** [qbcore-framework/qb-phone#379]
### Summary

press the key m no phone shows and no hud IE map and health

### Reproduction

This is a fresh public server with iceline so ive installed there qb core 2.2.4 come into game and phone doesn't come up nor does any map or health food drink on the hud also wont let me buy vehicles just leaves you stood in pdm doesn't spawn you in the vehicle just brought just takes money i have tried updating qb-phone and qb-core also tried hud as well but still the same don't get it haven't messed with anything 

now on the filp side i have a home hosted server again qbcore i made this before i joined iceline spent alot of time tweeking it to how i wanted it and building it never had a issue on my home hosted one just to add these are on different accounts and different keys 

### Expected behavior

to work

### Actual behavior

didn't

### Last Updated

today

### Custom Resources

none

### Resource Rename

no

**Comment by djraymond1** [comment]
all files are working for me so try reinstaling phone and hud

**Comment by madmechanic187** [comment]
i have man I've done it about 10 times  still no map health food drink phone and no speedo when in car none of the apartments let you in either

**Comment by MafewTM** [comment]
If it works perfectly fine when its home hosted, then its your host which also isnt an authorized service provider for FiveM servers.

**Comment by madmechanic187** [comment]
yeah like I say on my home host witch is on a different cfx account works no problems but with iceline live made a new cfx account key with there ip fresh install of qb core on there site and getting all these problems they say for me to come on here and download the up to date resources IE qb core qb phone it worked one time but now no joy tried it about 10 times but no one else seems to have a issue they say lots of customers are using the qb core with out any issues just had enough only wanted my server online put so much time into it and now its been about a week or two for messing about as theses issues

so what do you mean they arnt authorized so they have ripped me off with this messing about?
