### ISSUE TITLE
Apps not showing

### ISSUE THREAD

**Issue by Mashallgamer** [qbcore-framework/qb-phone#384]
### Summary

Apps not showing

### Reproduction

While opening the qb-phone on the key "m", the phone opens but it doesn't ahow any icon/apps
Also the "home" button on the phone, just closes the phone

Van someone help me?

Fivem version b2944

Thanks

### Expected behavior

Doesnt show any apps on the phone
Black acreen with the QB Core logo

### Actual behavior

Doesn't show any apps on the phone
Black acreen with the QB Core logo

### Last Updated

Just now

### Custom Resources

Qb-phone

### Resource Rename

Qb-phone

**Comment by itzzjd123** [comment]
@Mashallgamer Same here man let me know if you here of any fix...

**Comment by lak1z-azk** [comment]
Check the errors in F8 console. Might be something not setup.

**Comment by VRSDevelopment** [comment]
same issue here. please tell me anyone how i fix this

**Comment by VRSDevelopment** [comment]
> @VRSDevelopment what errors are shown in F8 console?

nothing showing there.

**Comment by lak1z-azk** [comment]
Check Live Console then on you citizenfx dashboard, there should be list of errors after you restart/start the resource

**Comment by Mashallgamer** [comment]
I did it by my own
Got no help from anywhere

**Comment by Mashallgamer** [comment]
it doesn't show any error in anywhere
All is runing, you just need to edit the .lua file

**Comment by timbalk** [comment]
@Mashallgamer How did you end up fixing it? im stuck here

**Comment by lak1z-azk** [comment]
@timbalk I think I know what could be the issue, but would be good to have detailed info and what errors do you get, as sometimes it could be a simple issue, that could be visible in Server Logs or via F8 in game console log.  If its not hard for you, we could jump to discord

**Comment by itzzjd123** [comment]
@timbalk @lak1z-azk Could someone please help me lol??

**Comment by lak1z-azk** [comment]
> @timbalk @lak1z-azk Could someone please help me lol??

drop your discord,I will reach you out in the morning my time and when you will be able to reply, I could try help you out with the issue :)

**Comment by itzzjd123** [comment]
Hey sorry I am a very busy person just now seeing this. My discord is itzzjd

**Comment by MazeRPserver** [comment]
i fixed it !! delete garages from ur fxmanifest.lua

**Comment by itzzjd123** [comment]
@MazeRPserver that didn't work

**Comment by itzzjd123** [comment]
@lak1z-azk hey sorry i will have plenty time tomorrow to talk about the problem ill hyu on discord right now

**Comment by Townyo420** [comment]
> i fixed it !! delete garages from ur fxmanifest.lua

THIS HELPED ME THANK YOU SO FUCKING MUCH
