### ISSUE TITLE
[BUG] PHONE NOT WORKING

### ISSUE THREAD

**Issue by itzzjd123** [qbcore-framework/qb-phone#385]
### Summary

I can open the phone but the nothing shows on the phone. Apps , nothing.

### Reproduction

......n/a

### Expected behavior

......n/a

### Actual behavior

.....n/a

### Last Updated

n/a

### Custom Resources

no

### Resource Rename

no

**Comment by Jord-0** [comment]
@itzzjd123 Did you get this working?

**Comment by itzzjd123** [comment]
> @itzzjd123 Did you get this working?

@Jord-0 Not at all could you please help if you know how??
