### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Kedom1** [qbcore-framework/qb-phone#395]
### Summary

I've added a webhook for the camera and i have screenshot basic in resources and ensured. when I'm in game I can take a pictures but it doesn't show up in gallery.

### Reproduction

Created a webhook
pasted webhook into qb-phone/server/config
Ensured in server config

### Expected behavior

i had though i would be able to take pictures see them on discord and in game

### Actual behavior

i was able to take pictures see them on discord but not in game

### Last Updated

yesterday

### Custom Resources

none

### Resource Rename

qb-phone

**Comment by coba59** [comment]
that's caused by a webhook. Not qb core related. Just don't use webhooks anymore

**Comment by Kedom1** [comment]
> that's caused by a webhook. Not qb core related. Just don't use webhooks anymore

webhook is needed to even take a picture

**Comment by ArcousSoftware** [comment]
I'm having the same problem now

**Comment by 4onatabg** [comment]
Im having the same problem , but it was working perfect before . I don't change anything on the discord settings and the server script settings.

**Comment by coba59** [comment]
> > that's caused by a webhook. Not qb core related. Just don't use webhooks anymore
> 
> webhook is needed to even take a picture

im trying to help you. you dont need webhooks anymore to take a pic. just read a little why discord stop supporting that feature
