### ISSUE TITLE
 my email is not showing the date

### ISSUE THREAD

**Issue by nylanpro** [qbcore-framework/qb-phone#50]
hello , my email is not showing the date, but in SQL there is data, can anyone tell me what is the error?
https://imgur.com/vP3AMTZ
https://imgur.com/y5O04R8

**Comment by ihyajb** [comment]
Could not reproduce the issue. Please make sure all your scripts are updated. Thank you

![image](https://user-images.githubusercontent.com/66404074/129430980-387b5cd5-71e7-4d02-afd7-b9af07e7dc5d.png)
