### ISSUE TITLE
Typo in callback qb-phone:server:GetInfo

### ISSUE THREAD

**Issue by braydxnn** [qbcore-framework/qb-phone#59]
![image](https://user-images.githubusercontent.com/73808761/129430865-f996932e-5188-46c9-91d1-e315d0b39a16.png)

MetaData is defined but not used nor is the query, and name is equal to phone number when it should be the characters name

**Comment by GhzGarage** [comment]
The query is called if the player is offline

**Comment by braydxnn** [comment]
Yeah it fetches for metadata but never applies it anywhere
