### ISSUE TITLE
[Suggestion] to walk/drive while the phone is open

### ISSUE THREAD

**Issue by switc7** [qbcore-framework/qb-phone#73]

**Comment by ZhoNNz** [comment]
Just add setnuifocus to the openPhone() function in its footer.

    SetNuiFocus(true, true)
    SetNuiFocusKeepInput(true)

    Citizen.CreateThread(function()
        while true do
            Citizen.Wait(0)
            DisableControlAction(0,24, true) -- disable attack
            DisableControlAction(0,25, true) -- disable aim
            DisableControlAction(1, 140, true) -- Attack
            DisableControlAction(1, 141, true) -- Attack
            DisableControlAction(1, 142, true) -- Attack
            DisableControlAction(1, 24, true) -- Attack
            DisableControlAction(1, 257, true) -- Attack
            DisableControlAction(1, 263, true) -- Attack
            DisableControlAction(1, 264, true) -- Attack
        end
    end)
    

Disable actions here prevent you from attacking when left clicked while walking.

**Comment by farrukogangalee** [comment]
Hi, Dudes
I try to implement this, but now when I open the inventory and move the mouse, the camera rotates as well, what is happening?
o0
