### ISSUE TITLE
Phone invoice cant be paid if bill sender offline 

### ISSUE THREAD

**Issue by ARSSANTO** [qbcore-framework/qb-phone#87]
It will be more handy if the invoice can be paid if the biller  is offline but biller  can get paid the bill if need example 

qb-occasion  send  car money if  seller is offline

**Comment by ARSSANTO** [comment]
thanks for looking into my issue you guys are OPPPPP

**Comment by SamShanks1** [comment]
https://github.com/qbcore-framework/qb-phone/commit/6abda0784831ea0f4c1b2de33f3dd20d6f4f1140 fixed this
