### ISSUE TITLE
Whatsapp Messages

### ISSUE THREAD

**Issue by maisn3r** [qbcore-framework/qb-phone#89]
Hello,

Whatsapp app, when the player doesn't have somebody in the contacts, can't receive messages.

**Comment by maisn3r** [comment]
Latest phone update not pulling data from database, contacts, messages and etc.

**Comment by maisn3r** [comment]
I got it when this is happaning, if the player don't have chats with this number, getting nil table index from GetIndexByNumber function.

**Comment by IllInuz** [comment]
Fixed; https://github.com/qbcore-framework/qb-phone/commit/b53b3faa6682916efb9af450e1140292c4dc0ae8

@GhzGarage
