### ISSUE TITLE
download latest phone

### ISSUE THREAD

**Issue by Kromanic** [qbcore-framework/qb-phone#93]
So i downloaded the latest phone and i get this issue 
![image](https://user-images.githubusercontent.com/78902920/132157582-619e356a-4887-49b1-8320-07710bf80d26.png)
and my phone stay like this most of the time and then it goes back to normal
![image](https://user-images.githubusercontent.com/78902920/132157634-df2aacec-f4c1-4b57-ad7a-c948229f5c12.png)

**Comment by maisn3r** [comment]
You need to update your qb-garages.

**Comment by am3nd01m** [comment]
I have the same issue, all scripts are up to date.

**Comment by meistroburger** [comment]
Have the same issue…

**Comment by Kromanic** [comment]
> Have the same issue… But if you update your job forward and back its fixed

after i updated the newest garage here it fixs that issue

**Comment by meistroburger** [comment]
> Have the same issue… But if you update your job forward and back its fixed

The lastest qb-garage fixed it <3
