### ISSUE TITLE
Issue with opening phone since core update

### ISSUE THREAD

**Issue by bakerzone** [qbcore-framework/qb-phone#97]
Hi,

Since the latest core update, the below is thrown when opening the phone:

[     script:qb-phone] > TriggerCallback (@qb-core/server/functions.lua:78)
[     script:qb-phone] > handler (@qb-core/server/events.lua:119)
[     script:qb-phone] SCRIPT ERROR: @qb-phone/server/main.lua:64: attempt to call a nil value (field 'ExecuteSql')
[     script:qb-phone] > TriggerCallback (@qb-core/server/functions.lua:78)
[     script:qb-phone] > handler (@qb-core/server/events.lua:119)

Phone phone is also blank, upon selecting one of the round, where the icons should be, it shows a js script error on line 224.

Thanks

Angie

**Comment by bakerzone** [comment]
Hi,

I saw where I went wrong, but the phone is still blank for me, any idea on how to fix this?
![Screenshot 2021-09-09 195231](https://user-images.githubusercontent.com/63113526/132745912-8ac1c0ae-deca-4a08-9b6c-70264efe9502.png)

**Comment by evanillaa** [comment]
iIt works fine
Try to update your files

**Comment by bakerzone** [comment]
> iIt works fine
> Try to update your files

Hi, Thanks for checking, I rolled everything back last night, so it must be a dependency, I'll go through them again.
